// ===========================================================
// SMART TA'LIM — Arab tili 10-qism (Hayvonlar)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR10 = [
  // Uy hayvonlari
  ["حيوان أليف", "uy hayvoni"],
  ["بقرة", "sigir"],
  ["ثور", "ho'kiz"],
  ["عجل", "buzoq"],
  ["حصان", "ot"],
  ["فرس", "biya (to'liq ot)"],
  ["مهر", "xotortay"],
  ["حمار", "eshak"],
  ["بغل", "xachir"],
  ["جمل", "tuya"],
  ["ناقة", "urg'ochi tuya"],
  ["خروف", "qo'y"],
  ["شاة", "qo'y (birlik)"],
  ["نعجة", "sovliq"],
  ["كبش", "qo'chqor"],
  ["حمل", "qo'zichoq"],
  ["ماعز", "echki"],
  ["تيس", "takka (erkak echki)"],
  ["جدي", "uloq"],
  ["كلب", "it"],
  ["جرو", "kuchuk"],
  ["قطة", "mushuk"],
  ["هرة", "mushuk (ayol)"],
  ["قط", "mushuk (erkak)"],
  ["دجاجة", "tovuq"],
  ["ديك", "xo'roz"],
  ["فرخ", "jo'ja"],
  ["بط", "o'rdak"],
  ["أوزة", "g'oz"],
  ["حمامة", "kaptar"],
  ["عصفور", "chumchuq"],
  ["ديك رومي", "kurka"],
  ["سمانة", "bedana"],

  // Yovvoyi hayvonlar
  ["أسد", "sher"],
  ["لبؤة", "sher (ayol)"],
  ["نمر", "yo'lbars"],
  ["فهد", "gepard"],
  ["دب", "ayiq"],
  ["ذئب", "bo'ri"],
  ["ثعلب", "tulki"],
  ["ضبع", "sirtlon"],
  ["فيل", "fil"],
  ["زرافة", "jirafa"],
  ["حمار وحشي", "zebra"],
  ["وحيد القرن", "karkidon"],
  ["فرس النهر", "begemot"],
  ["تمساح", "timsoh"],
  ["غزال", "kiyik (gazel)"],
  ["ظبي", "ohu"],
  ["قرد", "maymun"],
  ["سنجاب", "olmaxon"],
  ["أرنب", "quyon"],
  ["فأر", "sichqon"],
  ["جرذ", "kala"],
  ["قنفذ", "tipratikan"],
  ["خفاش", "ko'rshapalak"],
  ["سلحفاة", "toshbaqa"],
  ["ضفدع", "qurbaqa"],
  ["سحلية", "kaltakesak"],
  ["ثعبان", "ilon"],
  ["أفعى", "bo'g'ma ilon"],
  ["عقرب", "chayon"],

  // Qushlar
  ["طائر", "qush"],
  ["نسر", "burgut"],
  ["صقر", "lochin"],
  ["باز", "qarchig'ay"],
  ["بومة", "boyqush"],
  ["غراب", "qarg'a"],
  ["لقلق", "laylak"],
  ["طاووس", "tovus"],
  ["ببغاء", "to'tiqush"],
  ["نقار الخشب", "qizilishton"],
  ["هدهد", "hudhud (popishak)"],
  ["بطريق", "pingvin"],
  ["خطاف", "baliqchi qush"],
  ["دوري", "chumchuq (dori)"],
  ["نورس", "chag'alay"],

  // Dengiz hayvonlari
  ["سمكة", "baliq"],
  ["قرش", "akula"],
  ["دولفين", "delfin"],
  ["حوت", "kit"],
  ["أخطبوط", "sakkizoyoq"],
  ["قنديل البحر", "meduza"],
  ["سلطعون", "krab"],
  ["روبيان", "krevetka"],
  ["محار", "ustritsa"],
  ["نجم البحر", "dengiz yulduzi"],
  ["سلحفاة بحرية", "dengiz toshbaqasi"],

  // Hasharotlar
  ["حشرة", "hasharot"],
  ["نحلة", "asalari"],
  ["دبور", "ari"],
  ["ذبابة", "pashsha"],
  ["بعوضة", "chivin"],
  ["نملة", "chumoli"],
  ["فراشة", "kapalak"],
  ["عنكبوت", "o'rgimchak"],
  ["جندب", "chigirtka"],
  ["صرصور", "suvarak"],
  ["خنفساء", "qo'ng'iz"],
  ["جرادة", "malaxka"],
  ["يرقة", "qurt"],
  ["دودة", "chuvalchang"],
  ["برغوث", "burga"],
  ["قملة", "bit"],

  // Umumiy
  ["حيوان", "hayvon"],
  ["مخلوق", "jonzot"],
  ["فريسة", "o'lja"],
  ["مفترس", "yirtqich"],
  ["قطيع", "poda"],
  ["سرب", "qush to'dasi"],
  ["حديقة حيوان", "hayvonot bog'i"],
  ["عرين", "uyi (hayvon)"],
  ["جحر", "in (uya)"],
  ["ريش", "pat"],
  ["قرن", "shox (hayvonda)"],
  ["ذيل", "dum"],
  ["مخلب", "panja (tirnoq)"],
  ["ريش الطيور", "qush patlari"],
  ["زيز", "jumjima (chigirtka ovozi)"],
];