// Ingliz - O'zbek lug'at
// Har bir so'z: { en: "inglizcha", uz: "o'zbekcha" }
// Buni lugat.html ichidagi mavjud so'zlar massiviga qo'shing,
// yoki agar massiv nomi boshqacha bo'lsa (masalan `words` yoki `dictionary`),
// shu massiv nomini ishlatib qo'ying.

const words = [
  // Oila va odamlar
  { en: "family", uz: "oila" },
  { en: "mother", uz: "ona" },
  { en: "father", uz: "ota" },
  { en: "brother", uz: "aka/uka" },
  { en: "sister", uz: "opa/singil" },
  { en: "friend", uz: "do'st" },
  { en: "child", uz: "bola" },
  { en: "teacher", uz: "o'qituvchi" },
  { en: "student", uz: "talaba/o'quvchi" },
  { en: "neighbor", uz: "qo'shni" },

  // Ta'lim
  { en: "school", uz: "maktab" },
  { en: "university", uz: "universitet" },
  { en: "book", uz: "kitob" },
  { en: "lesson", uz: "dars" },
  { en: "homework", uz: "uy vazifasi" },
  { en: "exam", uz: "imtihon" },
  { en: "knowledge", uz: "bilim" },
  { en: "library", uz: "kutubxona" },
  { en: "notebook", uz: "daftar" },
  { en: "pen", uz: "ruchka" },
  { en: "pencil", uz: "qalam" },
  { en: "classroom", uz: "sinf xonasi" },
  { en: "question", uz: "savol" },
  { en: "answer", uz: "javob" },
  { en: "grade", uz: "baho" },
  { en: "degree", uz: "diplom/daraja" },
  { en: "scholarship", uz: "stipendiya" },
  { en: "lecture", uz: "ma'ruza" },
  { en: "research", uz: "tadqiqot" },
  { en: "science", uz: "fan" },

  // Kundalik hayot
  { en: "house", uz: "uy" },
  { en: "food", uz: "ovqat" },
  { en: "water", uz: "suv" },
  { en: "bread", uz: "non" },
  { en: "tea", uz: "choy" },
  { en: "morning", uz: "ertalab" },
  { en: "evening", uz: "kechqurun" },
  { en: "night", uz: "tun" },
  { en: "day", uz: "kun" },
  { en: "week", uz: "hafta" },
  { en: "month", uz: "oy" },
  { en: "year", uz: "yil" },
  { en: "time", uz: "vaqt" },
  { en: "work", uz: "ish" },
  { en: "money", uz: "pul" },
  { en: "city", uz: "shahar" },
  { en: "village", uz: "qishloq" },
  { en: "street", uz: "ko'cha" },
  { en: "car", uz: "mashina" },
  { en: "road", uz: "yo'l" },

  // Fe'llar
  { en: "to read", uz: "o'qimoq" },
  { en: "to write", uz: "yozmoq" },
  { en: "to speak", uz: "gapirmoq" },
  { en: "to listen", uz: "eshitmoq" },
  { en: "to understand", uz: "tushunmoq" },
  { en: "to learn", uz: "o'rganmoq" },
  { en: "to teach", uz: "o'qitmoq" },
  { en: "to go", uz: "bormoq" },
  { en: "to come", uz: "kelmoq" },
  { en: "to eat", uz: "yemoq" },
  { en: "to drink", uz: "ichmoq" },
  { en: "to sleep", uz: "uxlamoq" },
  { en: "to work", uz: "ishlamoq" },
  { en: "to help", uz: "yordam bermoq" },
  { en: "to think", uz: "o'ylamoq" },
  { en: "to know", uz: "bilmoq" },
  { en: "to want", uz: "xohlamoq" },
  { en: "to love", uz: "sevmoq" },
  { en: "to live", uz: "yashamoq" },
  { en: "to buy", uz: "sotib olmoq" },

  // Sifatlar
  { en: "good", uz: "yaxshi" },
  { en: "bad", uz: "yomon" },
  { en: "big", uz: "katta" },
  { en: "small", uz: "kichik" },
  { en: "new", uz: "yangi" },
  { en: "old", uz: "eski" },
  { en: "beautiful", uz: "chiroyli" },
  { en: "difficult", uz: "qiyin" },
  { en: "easy", uz: "oson" },
  { en: "fast", uz: "tez" },
  { en: "slow", uz: "sekin" },
  { en: "important", uz: "muhim" },
  { en: "interesting", uz: "qiziqarli" },
  { en: "happy", uz: "baxtli" },
  { en: "strong", uz: "kuchli" },

  // Vaqt va sonlar
  { en: "today", uz: "bugun" },
  { en: "tomorrow", uz: "ertaga" },
  { en: "yesterday", uz: "kecha" },
  { en: "now", uz: "hozir" },
  { en: "always", uz: "doim" },
  { en: "never", uz: "hech qachon" },
  { en: "one", uz: "bir" },
  { en: "two", uz: "ikki" },
  { en: "three", uz: "uch" },
  { en: "ten", uz: "o'n" },
  { en: "hundred", uz: "yuz" },
  { en: "thousand", uz: "ming" },

  // Tabiat
  { en: "sun", uz: "quyosh" },
  { en: "moon", uz: "oy (osmon)" },
  { en: "star", uz: "yulduz" },
  { en: "sky", uz: "osmon" },
  { en: "earth", uz: "yer" },
  { en: "mountain", uz: "tog'" },
  { en: "river", uz: "daryo" },
  { en: "sea", uz: "dengiz" },
  { en: "tree", uz: "daraxt" },
  { en: "flower", uz: "gul" },
  { en: "rain", uz: "yomg'ir" },
  { en: "snow", uz: "qor" },
  { en: "wind", uz: "shamol" },
  { en: "weather", uz: "ob-havo" },

  // Texnologiya
  { en: "computer", uz: "kompyuter" },
  { en: "phone", uz: "telefon" },
  { en: "internet", uz: "internet" },
  { en: "video", uz: "video" },
  { en: "application", uz: "ilova" },
  { en: "password", uz: "parol" },
  { en: "message", uz: "xabar" },
  { en: "screen", uz: "ekran" },

  // His-tuyg'u
  { en: "happiness", uz: "baxt" },
  { en: "sadness", uz: "qayg'u" },
  { en: "fear", uz: "qo'rquv" },
  { en: "hope", uz: "umid" },
  { en: "dream", uz: "orzu" },
  { en: "success", uz: "muvaffaqiyat" },
  { en: "effort", uz: "harakat" },
  { en: "patience", uz: "sabr" },
];

// Agar sahifangizda boshqa nom bilan chaqirilsa (masalan window.dictionaryData),
// pastdagi qatorni ehtiyojga qarab o'zgartiring:
// window.dictionaryData = words;
