// ===========================================================
// SMART TA'LIM — Arab tili 1-qism (Asosiy so'zlar)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR1 = [
  // Salomlashish
  ["مرحبا", "salom"],
  ["السلام عليكم", "assalomu alaykum"],
  ["وعليكم السلام", "va alaykum assalom"],
  ["صباح الخير", "xayrli tong"],
  ["مساء الخير", "xayrli kech"],
  ["ليلة سعيدة", "xayrli tun"],
  ["مع السلامة", "xayr"],
  ["إلى اللقاء", "ko'rishguncha"],
  ["كيف حالك", "qandaysan"],
  ["بخير", "yaxshiman"],
  ["شكرا", "rahmat"],
  ["شكرا جزيلا", "katta rahmat"],
  ["عفوا", "marhamat"],
  ["من فضلك", "iltimos"],
  ["نعم", "ha"],
  ["لا", "yo'q"],
  ["حسنا", "yaxshi (mayli)"],
  ["تمام", "joyida"],

  // Olmoshlar
  ["أنا", "men"],
  ["أنت", "sen"],
  ["أنتم", "siz"],
  ["نحن", "biz"],
  ["هو", "u (erkak)"],
  ["هي", "u (ayol)"],
  ["هم", "ular"],

  // Asosiy tushunchalar
  ["اسم", "ism"],
  ["كلمة", "so'z"],
  ["كتاب", "kitob"],
  ["قلم", "qalam"],
  ["بيت", "uy"],
  ["عالم", "olam"],
  ["حياة", "hayot"],
  ["موت", "o'lim"],
  ["زمان", "zamon"],
  ["مكان", "joy"],
  ["شيء", "narsa"],
  ["شخص", "shaxs"],
  ["رجل", "erkak"],
  ["امرأة", "ayol"],
  ["طفل", "bola"],
  ["ولد", "o'g'il bola"],
  ["بنت", "qiz"],
  ["صديق", "do'st"],
  ["عائلة", "oila"],
  ["مجتمع", "jamiyat"],
  ["قرار", "qaror"],
  ["فكرة", "g'oya"],
  ["سؤال", "savol"],
  ["جواب", "javob"],
  ["حق", "haq"],
  ["واجب", "majburiyat"],
  ["خطأ", "xato"],
  ["صواب", "to'g'ri"],

  // His-tuyg'u va holatlar
  ["خير", "yaxshilik"],
  ["شر", "yomonlik"],
  ["حب", "sevgi"],
  ["كره", "nafrat"],
  ["سعادة", "baxt"],
  ["حزن", "qayg'u"],
  ["فرح", "quvonch"],
  ["أمل", "umid"],
  ["خوف", "qo'rquv"],
  ["قوة", "kuch"],
  ["ضعف", "kuchsizlik"],
  ["علم", "ilm/bilim"],
  ["عمل", "ish"],
  ["تعب", "charchoq"],
  ["نوم", "uyqu"],
  ["طعام", "taom"],
  ["شراب", "ichimlik"],
  ["ماء", "suv"],
  ["خبز", "non"],
  ["لحم", "go'sht"],
  ["فاكهة", "meva"],
  ["خضار", "sabzavot"],
  ["ملح", "tuz"],
  ["سكر", "shakar"],
  ["زيت", "yog'"],

  // Vaqt va tabiat
  ["ليل", "tun"],
  ["نهار", "kunduz"],
  ["يوم", "kun"],
  ["سنة", "yil"],
  ["شهر", "oy (vaqt)"],
  ["وقت", "vaqt"],
  ["شمس", "quyosh"],
  ["قمر", "oy (osmon)"],
  ["نجم", "yulduz"],
  ["سماء", "osmon"],
  ["أرض", "yer"],
  ["نار", "olov"],
  ["هواء", "havo"],
  ["بحر", "dengiz"],
  ["جبل", "tog'"],
  ["طريق", "yo'l"],
  ["مدينة", "shahar"],
  ["قرية", "qishloq"],
  ["مسجد", "masjid"],
  ["نور", "nur"],
  ["ظلام", "zulmat"],
  ["صباح", "tong"],
];