// ===========================================================
// SMART TA'LIM — Lug'at 11-qism (Kiyim-kechak)
// Format: [inglizcha, o'zbekcha]
// ===========================================================

const LUGAT_CLOTHES = [
  // Kiyimlar
  ["dress", "ko'ylak"],
  ["skirt", "yubka"],
  ["blouse", "bluzka"],
  ["shirt", "erkaklar ko'ylagi"],
  ["t-shirt", "mayka"],
  ["trousers", "shim"],
  ["jeans", "jinsi"],
  ["shorts", "kalta shim"],
  ["coat", "palto"],
  ["jacket", "kurtka"],
  ["sweater", "kofta"],
  ["cardigan", "kardigan"],
  ["hoodie", "gudik/kiyim"],
  ["tracksuit", "sport kostyum"],
  ["suit", "kostyum"],
  ["vest", "yelek"],
  ["overall", "kombinezon"],
  ["raincoat", "yamg'ir paltosi"],
  ["fur coat", "mo'ynali palto"],
  ["woolen coat", "junning palto"],

  // Milliy va maxsus kiyimlar
  ["chasuble", "chopon"],
  ["robe", "xalat"],
  ["beanie", "doppi"],
  ["headscarf", "ro'mol"],
  ["skullcap", "keppak"],
  ["national dress", "milliy libos"],
  ["wedding dress", "kelinlik kiyimi"],
  ["pajamas", "piyama"],
  ["uniform", "forma"],
  ["apron", "fartuk"],

  // Ichki kiyim va aksessuarlar
  ["underwear", "ichki kiyim"],
  ["socks", "paypoq"],
  ["stockings", "kolgotka"],
  ["belt", "kamar"],
  ["tie", "galstuk"],
  ["scarf", "sharf"],
  ["gloves", "qo'lqop"],
  ["mittens", "qo'lqop (qo'llig'i)"],
  ["hat", "shlyapa"],
  ["cap", "furajka"],
  ["gown", "xalat (uzun)"],
  ["shawl", "shol"],
  ["handkerchief", "dastro'mol"],
  ["wallet", "hamyon"],
  ["watch", "qo'l soati"],
  ["ring", "uzuk"],
  ["bracelet", "bilaguzuk"],
  ["necklace", "marjon"],
  ["earrings", "sirg'a"],
  ["buckle", "to'g'a"],

  // Poyafzal
  ["shoes", "poyafzal"],
  ["boots", "etik"],
  ["sandals", "sandal"],
  ["slippers", "sip-sap"],
  ["sneakers", "krossovka"],
  ["high heels", "baland poshnali tufli"],
  ["moccasins", "mokasin"],
  ["lace", "bog'ich"],
  ["sole", "tagi"],
  ["heel", "poshna"],

  // Matolar va kiyim detallari
  ["cotton", "paxta"],
  ["silk", "ipak"],
  ["wool", "jun"],
  ["leather", "charm"],
  ["denim", "jinsi mato"],
  ["velvet", "baxmal"],
  ["synthetic", "sintetika"],
  ["button", "tugma"],
  ["zipper", "zamok"],
  ["pocket", "cho'ntak"],
  ["collar", "yoqa"],
  ["sleeve", "yeng"],
  ["hem", "etag"],
  ["seam", "chok"],
  ["stain", "dog'"],
  ["patch", "yamoq"],
  ["size", "o'lcham"],
  ["fitting room", "kiyim kiyish xonasi"],
  ["fashion", "moda"],
  ["style", "uslub/ko'rinish"],
];