// ===========================================================
// SMART TA'LIM — Arab tili 6-qism (Oziq-ovqat va ichimliklar)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR6 = [
  ["طعام", "taom"],
  ["إفطار", "nonushta"],
  ["غداء", "tushlik"],
  ["عشاء", "kechki ovqat"],
  ["وجبة", "ovqat (porciya)"],
  ["مقبلات", "meza"],
  ["حلوى", "shirinlik"],
  ["شوربة", "sho'rva"],
  ["سلطة", "salat"],
  ["لحم", "go'sht"],
  ["لحم بقري", "mol go'shti"],
  ["لحم غنم", "qo'y go'shti"],
  ["دجاج", "tovuq"],
  ["ديك رومي", "kurka"],
  ["سمك", "baliq"],
  ["روبيان", "qisqichbaqa"],
  ["بيض", "tuxum"],
  ["جبن", "pishloq"],
  ["زبدة", "sariyog'"],
  ["حليب", "sut"],
  ["لبن", "qatiq (suzma)"],
  ["قشدة", "qaymoq"],
  ["عسل", "asal"],
  ["مربى", "murabbo"],
  ["خبز", "non"],
  ["خبز أبيض", "oq non"],
  ["خبز أسمر", "qora non"],
  ["رز", "guruch"],
  ["معكرونة", "makaron"],
  ["شعيرية", "ugra/lapsha"],
  ["برغل", "bulg'or"],
  ["دقيق", "un"],
  ["فاصولياء", "loviya"],
  ["عدس", "yasmiq"],
  ["حمص", "no'xat"],
  ["بازلاء", "no'xat (yashil)"],
  ["بطاطس", "kartoshka"],
  ["بيلاف", "palov"],
  ["لحم مشوي", "kabob/gril"],
  ["شاورما", "shaurma"],
  ["منتو", "manti"],
  ["سمسة", "somsa"],
  ["حساء", "suyuq osh"],
  ["زيت زيتون", "zaytun yog'i"],
  ["زيت عباد الشمس", "kungaboqar yog'i"],
  ["خل", "sirka"],
  ["ملح", "tuz"],
  ["سكر", "shakar"],
  ["فلفل أسود", "qora qalampir"],
  ["فلفل أحمر", "qizil qalampir"],
  ["كمون", "zira"],
  ["قرفة", "dolchin"],
  ["زنجبيل", "zanjabil"],
  ["فانيليا", "vanil"],
  ["كباب", "kabob"],
  ["شيش طاووق", "shish tovuq"],
  ["طبق", "taom (buyurtma)"],
  ["صحن", "tarelka"],
  ["شوكة", "vilka"],
  ["سكين", "pichoq"],
  ["ملعقة", "qoshiq"],
  ["ملعقة شاي", "choy qoshiq"],
  ["كوب", "stakan"],
  ["زجاجة", "shisha (idish)"],
  ["إبريق", "ko'za"],
  ["فرن", "pech"],
  ["موقد", "plita"],
  ["ميكروويف", "mikroto'lqin"],
  ["ثلاجة", "muzlatgich"],
  ["ماء", "suv"],
  ["شاي", "choy"],
  ["قهوة", "qahva"],
  ["عصير", "sharbat"],
  ["عصير برتقال", "apelsin sharbati"],
  ["ليمونادة", "limonad"],
  ["مشروب غازي", "gazli ichimlik"],
  ["معجون الطماطم", "tomat pastasi"],
  ["صلصة", "sous"],
  ["كاتشب", "ketchup"],
  ["مايونيز", "mayonez"],
  ["مستردة", "xantal"],
  ["تفاح", "olma"],
  ["موز", "banan"],
  ["برتقال", "apelsin"],
  ["عنب", "uzum"],
  ["بطيخ", "tarvuz"],
  ["شمام", "qovun"],
  ["خوخ", "shaftoli"],
  ["كرز", "olcha"],
  ["فراولة", "qulupnay"],
  ["رمان", "anor"],
  ["تمر", "xurmo"],
  ["تين", "anjir"],
  ["لوز", "bodom"],
  ["جوز", "yong'oq"],
  ["فستق", "pista"],
  ["بندق", "funduk"],
  ["مشمش", "o'rik"],
];