// ===========================================================
// SMART TA'LIM — Arab tili 3-qism (Tana a'zolari)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR3 = [
  ["جسم", "badan/tana"],
  ["جسد", "jasad"],
  ["رأس", "bosh"],
  ["شعر", "soch"],
  ["وجه", "yuz"],
  ["جبهة", "peshona"],
  ["حاجب", "qosh"],
  ["عين", "ko'z"],
  ["عينان", "ko'zlar"],
  ["جفن", "ko'z qovog'i"],
  ["رموش", "kipriklar"],
  ["أنف", "burun"],
  ["منخر", "burun teshigi"],
  ["خد", "yonoq"],
  ["فم", "og'iz"],
  ["شفة", "lab"],
  ["شفتان", "lablar"],
  ["سن", "tish"],
  ["أسنان", "tishlar"],
  ["لسان", "til"],
  ["ذقن", "iyak"],
  ["فك", "jag'"],
  ["أذن", "quloq"],
  ["أذنان", "quloqlar"],
  ["رقبة", "bo'yin"],
  ["عنق", "bo'yin (orga qismi)"],
  ["حنجرة", "kekirdak"],
  ["حلوق", "tomoq"],
  ["كتف", "yelka"],
  ["ذراع", "qo'l (yuqori qismi)"],
  ["ساعد", "bilak"],
  ["مرفق", "tirsak"],
  ["رسغ", "bilak bo'g'imi"],
  ["كف", "kaft"],
  ["يد", "qo'l (panja)"],
  ["أصبع", "barmoq"],
  ["إبهام", "bosh barmoq"],
  ["سبابة", "ko'rsatkich barmoq"],
  ["ظفر", "tirnoq"],
  ["صدر", "ko'krak"],
  ["بطن", "qorin"],
  ["سرة", "kindik"],
  ["خاصرة", "biqin"],
  ["ظهر", "orqa"],
  ["عمود فقري", "umurtqa pog'onasi"],
  ["ضلع", "qovurg'a"],
  ["عظم", "suyak"],
  ["عظام", "suyaklar"],
  ["مفصل", "bo'g'im"],
  ["عضلة", "mushak"],
  ["جلد", "teri"],
  ["دم", "qon"],
  ["عرق", "ter (sweat)"],
  ["لحية", "soqol"],
  ["شارب", "mo'ylov"],
  ["قلب", "yurak"],
  ["رئة", "o'pka"],
  ["كبد", "jigar"],
  ["كلية", "buyrak"],
  ["مثانة", "qovuq"],
  ["مخ", "miya"],
  ["دماغ", "bosh miya"],
  ["عصب", "asab"],
  ["معدة", "oshqozon"],
  ["أمعاء", "ichaklar"],
  ["أمعاء دقيقة", "ingichka ichak"],
  ["أمعاء غليظة", "yo'g'on ichak"],
  ["مريء", "qizilo'ngach"],
  ["طحال", "taloq"],
  ["مرارة", "o't pufagi"],
  ["بنكرياس", "oshqozon osti bezi"],
  ["غدة", "bez"],
  ["هرمون", "gormon"],
  ["فخذ", "son"],
  ["ركبة", "tizza"],
  ["ساق", "boldir"],
  ["قدم", "oyoq"],
  ["كعب", "tovon"],
  ["مشط القدم", "oyoq panjasi"],
  ["روح", "ruh"],
  ["نفس", "nafas"],
  ["عقل", "aql"],
  ["ذاكرة", "xotira"],
  ["حاسة", "his (sezgi)"],
  ["ذوق", "ta'm bilish"],
  ["سمع", "eshitish"],
  ["بصر", "ko'rish"],
  ["شم", "hid bilish"],
  ["لمس", "sezish (tuyg'u)"],
  ["ضمير", "vijdon"],
  ["شهية", "ishtaha"],
  ["عطش", "chanqov"],
  ["جوع", "ochlik"],
  ["إرهاق", "charchoq (tanaviy)"],
  ["ألم", "og'riq"],
  ["صحة", "salomatlik"],
  ["مرض", "kasallik"],
  ["دواء", "dori"],
  ["ضمادة", "bint"],
  ["ميزان الحرارة", "termometr"],
  ["نبض", "puls"],
  ["ضغط الدم", "qon bosimi"],
  ["بصمة", "barmoq izi"],
  ["طول", "bo'y (uzunlik)"],
  ["وزن", "vazn/og'irlik"],
  ["عين حمراء", "qizargan ko'z"],
  ["نظرة", "qarash"],
  ["ابتسامة", "tabassum"],
];