// ===========================================================
// SMART TA'LIM — Arab tili 14-qism (Din va islom)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR14 = [
  ["إسلام", "islom"],
  ["إيمان", "iymon"],
  ["إحسان", "ehson"],
  ["دين", "din"],
  ["مسلم", "musulmon"],
  ["مؤمن", "mo'min"],
  ["كافر", "kofir"],
  ["الله", "Alloh"],
  ["رسول", "rasul"],
  ["نبي", "nabiy"],
  ["قرآن", "Qur'on"],
  ["سورة", "sura"],
  ["آية", "oyat"],
  ["حديث", "hadis"],
  ["سنة", "sunnat"],
  ["شريعة", "shariat"],
  ["فقه", "fiqh"],
  ["مسجد", "masjid"],
  ["مئذنة", "minora"],
  ["منبر", "minbar"],
  ["محراب", "mehrob"],
  ["مصلى", "musalla"],
  ["أذان", "azon"],
  ["مؤذن", "muazzin"],
  ["إمام", "imom"],
  ["خطيب", "xatib"],
  ["صلاة", "namoz"],
  ["صلاة الفجر", "bomdod namozi"],
  ["صلاة الظهر", "peshin namozi"],
  ["صلاة العصر", "asr namozi"],
  ["صلاة المغرب", "shom namozi"],
  ["صلاة العشاء", "xufton namozi"],
  ["صلاة الجمعة", "juma namozi"],
  ["صلاة التراويح", "tarovih namozi"],
  ["صلاة الجنازة", "janoza namozi"],
  ["ركعة", "rakat"],
  ["سجود", "sajda"],
  ["ركوع", "ruku"],
  ["قيام", "tik turish"],
  ["قعود", "o'tirish"],
  ["تشهد", "tashahhud"],
  ["سلام الختام", "salom (namoz oxiri)"],
  ["وضوء", "tahorat (yuvinish)"],
  ["غسل", "g'usl"],
  ["تيمم", "tayammum"],
  ["مسح", "mash (surtish)"],
  ["نية", "niyat"],
  ["تكبير", "takbir"],
  ["سبحان الله", "Subhanalloh"],
  ["الحمد لله", "Alhamdulillah"],
  ["الله أكبر", "Allohu akbar"],
  ["استغفار", "istig'for"],
  ["دعاء", "duo"],
  ["ذكر", "zikr"],
  ["تسبيح", "tasbeh"],
  ["صدقة", "sadaqa"],
  ["زكاة", "zakot"],
  ["حج", "haj"],
  ["عمرة", "umra"],
  ["إحرام", "ihrom"],
  ["عرفة", "Arofa"],
  ["كعبة", "Ka'ba"],
  ["منى", "Mino"],
  ["مزدلفة", "Muzdalifa"],
  ["رمي الجمرات", "jimar otish"],
  ["طواف", "tavof"],
  ["سعي", "sa'y"],
  ["صيام", "ro'za"],
  ["إفطار", "iftor"],
  ["سحور", "saharlik"],
  ["رمضان", "Ramazon"],
  ["عيد الفطر", "Ramazon hayiti"],
  ["عيد الأضحى", "Qurbon hayiti"],
  ["قربان", "qurbonlik"],
  ["أضحية", "qurbon (hadya)"],
  ["فطر", "fitr"],
  ["خمس", "xums"],
  ["طهارة", "poklik"],
  ["إباحة", "joiz (ruxsat)"],
  ["حرام", "harom"],
  ["حلال", "halol"],
  ["مكروه", "makruh"],
  ["مستحب", "mustahab"],
  ["فرض", "farz"],
  ["واجب", "vojib"],
  ["سنة مؤكدة", "muakkad sunnat"],
  ["عمل صالح", "savobli amal"],
  ["ثواب", "savob"],
  ["ذنب", "gunoh"],
  ["توبة", "tavba"],
  ["آخرة", "oxirat"],
  ["جنة", "jannat"],
  ["نار", "do'zax"],
  ["صراط", "sirot"],
  ["خالق", "Xoliq (yaratuvchi)"],
  ["رحمن", "Rahmon"],
  ["رحيم", "Rahim"],
  ["قدر", "taqdir"],
  ["رزق", "rizq"],
  ["بركة", "baraka"],
  ["إخلاص", "ixlos"],
  ["تقوى", "taqvo"],
  ["شهيد", "shahid"],
  ["مجاهد", "mujohid"],
  ["مسلم جديد", "yangi musulmon"],
  ["داعية", "da'vatchi"],
  ["حافظ", "hofiz"],
  ["عالم دين", "mutasavvuf (olim)"],
  ["مفتي", "muftiy"],
  ["جمعة", "juma"],
  ["مصاحف", "mus-haf (Qur'on)"],
  ["خطبة", "xutba"],
  ["عيد", "hayit"],
];