// ===========================================================
// SMART TA'LIM — Arab tili 5-qism (Ta'lim va fan)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR5 = [
  ["مدرسة", "maktab"],
  ["جامعة", "universitet"],
  ["كلية", "fakultet"],
  ["صف", "sinf"],
  ["مدرس", "o'qituvchi"],
  ["معلم", "muallim"],
  ["أستاذ", "professor"],
  ["طالب", "talaba"],
  ["تلميذ", "o'quvchi"],
  ["زميل", "kursdosh"],
  ["مدير مدرسة", "maktab direktori"],
  ["مكتبة", "kutubxona"],
  ["كتاب", "kitob"],
  ["دفتر", "daftar"],
  ["قلم", "qalam"],
  ["قلم رصاص", "qalam (sodda)"],
  ["ممحاة", "o'chirg'ich"],
  ["سبورة", "doska"],
  ["طبشور", "bo'r"],
  ["حقيبة مدرسية", "maktab sumkasi"],
  ["درس", "dars"],
  ["حصة", "mashg'ulot"],
  ["واجب منزلي", "uy vazifasi"],
  ["امتحان", "imtihon"],
  ["اختبار", "test"],
  ["درجة", "baho"],
  ["نتيجة", "natija"],
  ["شهادة", "shahodatnoma"],
  ["ديبلوم", "diplom"],
  ["بحث", "tadqiqot"],
  ["مقال", "maqola"],
  ["مشروع", "loyiha"],
  ["نظرية", "nazariya"],
  ["قانون", "qonun (qoida)"],
  ["مبدأ", "prinsip"],
  ["تجربة", "tajriba (eksperiment)"],
  ["ملاحظة", "kuzatuv"],
  ["استنتاج", "xulosa"],
  ["فرضية", "faraz"],
  ["دليل", "dalil"],
  ["برهان", "isbot"],
  ["تعريف", "ta'rif"],
  ["مصطلح", "atama"],
  ["معنى", "ma'no"],
  ["ترجمة", "tarjima"],
  ["لغة", "til"],
  ["قواعد", "grammatika"],
  ["مفردات", "lug'at (so'z boyligi)"],
  ["حرف", "harf"],
  ["حروف", "harflar"],
  ["كلمة", "so'z"],
  ["جملة", "gap/jumla"],
  ["فقرة", "paragraf"],
  ["فصل", "bo'lim"],
  ["باب", "bob"],
  ["صفحة", "sahifa"],
  ["عنوان", "sarlavha"],
  ["خلاصة", "qisqacha xulosa"],
  ["مقدمة", "kirish"],
  ["خاتمة", "xotima"],
  ["رياضيات", "matematika"],
  ["فيزياء", "fizika"],
  ["كيمياء", "kimyo"],
  ["أحياء", "biologiya"],
  ["فلك", "astronomiya"],
  ["جيولوجيا", "geologiya"],
  ["جغرافيا", "geografiya"],
  ["تاريخ", "tarix"],
  ["فلسفة", "falsafa"],
  ["منطق", "mantiq"],
  ["علم النفس", "psixologiya"],
  ["علم الاجتماع", "sotsiologiya"],
  ["إحصاء", "statistika"],
  ["محاسبة", "buxgalteriya"],
  ["أدب", "adabiyot"],
  ["شعر", "she'r"],
  ["نثر", "nasr"],
  ["مسرح", "teatr"],
  ["موسيقى", "musiqa"],
  ["فن", "san'at"],
  ["رسالة", "xat/xabar"],
  ["محاضرة", "ma'ruza"],
  ["ندوة", "seminar"],
  ["مؤتمر", "konferensiya"],
  ["قراءة", "o'qish"],
  ["كتابة", "yozish"],
  ["حفظ", "yodlash"],
  ["فهم", "tushunish"],
  ["تفكير", "fikrlash"],
  ["تحليل", "tahlil"],
  ["نقد", "tanqid"],
  ["تعلم", "o'rganish"],
  ["تعليم", "ta'lim/o'qitish"],
  ["تدريب", "mashq/trenirovka"],
  ["تربية", "tarbiya"],
  ["ثقافة", "madaniyat"],
  ["معرفة", "bilim"],
  ["معلومات", "ma'lumot"],
  ["ذكاء", "aql-zakovat"],
  ["موهبة", "iste'dod"],
  ["عبقرية", "daholik"],
  ["اجتهاد", "tirishqoqlik"],
  ["تفوق", "o'zib ketish (muvaffaqiyat)"],
  ["منحة", "stipendiya"],
  ["عود", "ta'lim olish"],
];