// ===========================================================
// SMART TA'LIM — Lug'at 6-qism (Uy va jihozlar)
// Format: [inglizcha, o'zbekcha]
// ===========================================================

const LUGAT_HOUSE = [
  // Uy qismlari va xonalar
  ["house", "uy"],
  ["home", "uy (makon)"],
  ["apartment", "kvartira"],
  ["building", "bino"],
  ["floor", "qavat"],
  ["room", "xona"],
  ["kitchen", "oshxona"],
  ["bedroom", "yotoqxona"],
  ["bathroom", "hammom"],
  ["toilet", "hojatxona"],
  ["living room", "mehmonxona"],
  ["hallway", "yo'lak"],
  ["balcony", "balkon"],
  ["roof", "tom"],
  ["wall", "devor"],
  ["floor", "pol"],
  ["ceiling", "ship"],
  ["window", "deraza"],
  ["door", "eshik"],
  ["stairs", "zinapoya"],
  ["garage", "garaj"],
  ["garden", "bog'"],
  ["yard", "hovli"],
  ["fence", "panjara"],
  ["gate", "darvoza"],

  // Mebel va jihozlar
  ["table", "stol"],
  ["chair", "stul"],
  ["sofa", "divan"],
  ["bed", "karavot"],
  ["wardrobe", "shkaf"],
  ["closet", "javon"],
  ["bookshelf", "kitob javoni"],
  ["desk", "parta/yozuv stoli"],
  ["mirror", "oyna"],
  ["carpet", "gilam"],
  ["curtain", "parda"],
  ["pillow", "yostiq"],
  ["blanket", "ko'rpa"],
  ["mattress", "matras"],
  ["cushion", "yostiqcha"],
  ["lamp", "chiroq"],
  ["fan", "ventilyator"],
  ["heater", "isitgich"],
  ["radiator", "radiator"],
  ["air conditioner", "konditsioner"],
  ["clock", "soat (devor)"],
  ["chandelier", "lyustra"],

  // Oshxona idishlari
  ["plate", "tarelka"],
  ["bowl", "piyola"],
  ["cup", "chashka"],
  ["glass", "stakan"],
  ["spoon", "qoshiq"],
  ["fork", "vilka"],
  ["knife", "pichoq"],
  ["teapot", "choynak"],
  ["kettle", "cho'yun qumg'on"],
  ["pan", "tova"],
  ["pot", "kastrul"],
  ["frying pan", "skovorodka"],
  ["oven", "pech"],
  ["stove", "plita"],
  ["refrigerator", "muzlatgich"],
  ["dishwasher", "idish yuvish mashinasi"],
  ["microwave", "mikroto'lqinli pech"],
  ["toaster", "toster"],
  ["blender", "blender"],
  ["cutter", "kesish taxtasi"],

  // Xo'jalik va tozalash buyumlari
  ["broom", "supurgi"],
  ["bucket", "chelak"],
  ["mop", "shvabbra"],
  ["soap", "sovun"],
  ["shampoo", "shampun"],
  ["toothbrush", "tish cho'tkasi"],
  ["towel", "sochiq"],
  ["laundry", "kir yuvish"],
  ["washing machine", "kir yuvish mashinasi"],
  ["vacuum cleaner", "chang yutgich"],
  ["iron", "dazmol"],
  ["detergent", "kir yuvish kukuni"],
  ["sponge", "gubka"],
  ["trash can", "axlat chelagi"],
  ["plug", "vilka"],
  ["socket", "rozetka"],
  ["switch", "kalit"],
  ["battery", "batareya"],
  ["bulb", "lampochka"],
  ["remote control", "pult"],
];