// ===========================================================
// SMART TA'LIM — Lug'at 5-qism (Tana va salomatlik)
// Format: [inglizcha, o'zbekcha]
// ===========================================================

const LUGAT_HEALTH = [
  // Tana a'zolari
  ["head", "bosh"],
  ["hair", "soch"],
  ["face", "yuz"],
  ["eye", "ko'z"],
  ["eyebrow", "qosh"],
  ["eyelash", "kiprik"],
  ["ear", "quloq"],
  ["nose", "burun"],
  ["mouth", "og'iz"],
  ["tooth", "tish"],
  ["tongue", "til"],
  ["lip", "lab"],
  ["chin", "iyak"],
  ["cheek", "yonoq"],
  ["forehead", "peshona"],
  ["neck", "bo'yin"],
  ["shoulder", "yelka"],
  ["arm", "qo'l"],
  ["elbow", "tirsak"],
  ["hand", "qo'l (panja)"],
  ["finger", "barmoq"],
  ["wrist", "bilak"],
  ["chest", "ko'krak"],
  ["back", "orqa"],
  ["stomach", "qorin"],
  ["waist", "bel"],
  ["leg", "oyoq"],
  ["knee", "tizza"],
  ["foot", "oyog' panjasi"],
  ["toe", "oyoq barmog'i"],
  ["heel", "tovon"],
  ["ankle", "to'piq"],
  ["heart", "yurak"],
  ["lung", "o'pka"],
  ["liver", "jigar"],
  ["kidney", "buyrak"],
  ["brain", "miya"],
  ["bone", "suyak"],
  ["muscle", "mushak"],
  ["blood", "qon"],
  ["skin", "teri"],
  ["vein", "vena/tomir"],
  ["nerve", "asab"],

  // Kasallik va salomatlik
  ["health", "sog'liq"],
  ["disease", "kasallik"],
  ["illness", "xastalik"],
  ["flu", "gripp"],
  ["cold", "shamollash"],
  ["fever", "isitma"],
  ["cough", "yo'tal"],
  ["headache", "bosh og'rig'i"],
  ["toothache", "tish og'rig'i"],
  ["sore throat", "tomog' og'rig'i"],
  ["stomach ache", "oshqozon og'rig'i"],
  ["pain", "og'riq"],
  ["injury", "jarohat"],
  ["wound", "yara"],
  ["fracture", "sinish"],
  ["infection", "infeksiya"],
  ["allergy", "allergiya"],
  ["diabetes", "qand kasalligi"],
  ["pressure", "bosim"],
  ["pulse", "puls"],

  // Tibbiy xizmat
  ["doctor", "shifokor"],
  ["nurse", "hamshira"],
  ["patient", "bemor"],
  ["hospital", "kasalxona"],
  ["clinic", "poliklinika"],
  ["pharmacy", "dorixona"],
  ["medicine", "dori"],
  ["pill", "tabletka"],
  ["injection", "ukol"],
  ["bandage", "bint"],
  ["thermometer", "termometr"],
  ["ambulance", "tez yordam"],
  ["operation", "operatsiya"],
  ["check-up", "tekshiruv"],
  ["visiting hours", "qabul vaqti"],
  ["recovery", "tuzalish"],
  ["rest", "dam olish"],
  ["exercise", "jismoniy mashq"],
  ["vitamin", "vitamin"],
  ["immunity", "immunitet"],

  // His-tuyg'u va holatlar
  ["tired", "charchagan"],
  ["healthy", "sog'lom"],
  ["weak", "kuchsiz"],
  ["strong", "kuchli"],
  ["sick", "kasal"],
  ["dizzy", "boshi aylangan"],
  ["nausea", "ko'ngil aynish"],
  ["hungry", "och"],
  ["thirsty", "chanqagan"],
  ["asleep", "uxlab qolgan"],
];