// ===========================================================
// SMART TA'LIM — Arab tili 12-qism (Sport va dam olish)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR12 = [
  ["رياضة", "sport"],
  ["رياضات", "sport turlari"],
  ["مباراة", "o'yin (musobaqa)"],
  ["بطولة", "chempionat"],
  ["كأس", "kubok"],
  ["ميدالية", "medal"],
  ["جائزة", "mukofot/sovrin"],
  ["لاعب", "o'yinchi"],
  ["فريق", "jamoa"],
  ["مدرب", "murabbiy"],
  ["حكم", "hakam"],
  ["مشجع", "muxlis"],
  ["جمهور", "tomoshabinlar"],
  ["ملعب", "stadion"],
  ["صالة رياضية", "sport zal"],
  ["مسبح", "basseyn"],
  ["كرة قدم", "futbol"],
  ["كرة السلة", "basketbol"],
  ["كرة الطائرة", "voleybol"],
  ["كرة اليد", "gandbol"],
  ["تنس", "tennis"],
  ["تنس الطاولة", "stol tennisi"],
  ["تنس الريشة", "badminton"],
  ["ملاكمة", "boks"],
  ["مصارعة", "kurash"],
  ["جودو", "dzyudo"],
  ["كاراتيه", "karate"],
  ["سباحة", "suzish"],
  ["غطس", "sho'ng'ish"],
  ["سباق", "poyga"],
  ["جري", "yugurish"],
  ["ماراثون", "marafon"],
  ["دراجة", "velosiped"],
  ["سباق دراجات", "velopoyga"],
  ["فروسية", "ot sporti"],
  ["رماية", "otish (kamondan)"],
  ["قوس وسهم", "kamon va o'q"],
  ["رفع الأثقال", "og'ir atletika"],
  ["جمباز", "gimnastika"],
  ["هوكي", "xokkey"],
  ["كريكيت", "kriket"],
  ["غولف", "golf"],
  ["رجبي", "regbi"],
  ["بيسبول", "beysbol"],
  ["اسكواش", "skvosh"],
  ["تسلق جبال", "tog'ga chiqish"],
  ["رحلات", "sayohat"],
  ["تخييم", "camping"],
  ["تنزه", "sayr"],
  ["صيد الأسماك", "baliq ovlash"],
  ["قفز بالمظلة", "parashyutdan sakrash"],
  ["بلياردو", "bilyard"],
  ["بولينغ", "bouling"],
  ["شطرنج", "shaxmat"],
  ["لعبة الداما", "shashka"],
  ["بطاقات", "kartalar"],
  ["نرد", "zar (tavla)"],
  ["ألعاب الفيديو", "video o'yinlar"],
  ["لعبة", "o'yin"],
  ["لعب", "o'ynash"],
  ["تسلية", "o'yin-kulgi"],
  ["هواية", "sevimli mashg'ulot"],
  ["اهتمام", "qiziqish"],
  ["إجازة", "ta'til"],
  ["يوم عطلة", "dam olish kuni"],
  ["راحة", "dam olish"],
  ["استرخاء", "bo'shashish"],
  ["نزهة", "pinik"],
  ["حديقة عامة", "istirohat bog'i"],
  ["سينما", "kino"],
  ["مسرح", "teatr"],
  ["حفل", "ziyofat/konsert"],
  ["حفلة موسيقية", "musiqiy konsert"],
  ["رقص", "raqs"],
  ["غناء", "qo'shiq aytish"],
  ["قراءة", "kitob o'qish"],
  ["رسم", "rasm chizish"],
  ["تصوير", "suratga olish"],
  ["طبخ", "ovqat pishirish"],
  ["خياطة", "tikuvchilik"],
  ["حياكة", "to'qish"],
  ["بستنة", "bog'dorchilik"],
  ["خط", "xattotlik"],
  ["موسيقى", "musiqa"],
  ["آلات موسيقية", "musiqa asboblari"],
  ["رحلة مدرسية", "maktab sayohati"],
  ["رحلة", "sayohat"],
  ["متنزه", "dam olish maskani"],
  ["مدينة الملاهي", "atraktsionlar"],
  ["ألعاب نارية", "salyut"],
  ["نشاط", "faoliyat"],
  ["فراغ", "bo'sh vaqt"],
  ["متحف", "muzey"],
  ["معرض", "ko'rgazma"],
  ["مكتبة", "kutubxona"],
  ["كافيه", "kafe"],
  ["مطعم", "restoran"],
  ["نادٍ", "klub"],
  ["إستاد", "stadion (arenal)"],
  ["مضمار", "yugurish yo'lagi"],
  ["كرة", "to'p"],
  ["مرمى", "darvoza (gol)"],
  ["تسجيل", "gol kiritish"],
  ["تعادل", "durang"],
  ["نصر", "g'alaba"],
  ["هزيمة", "mag'lubiyat"],
  ["رياضي", "sportchi"],
  ["لياقة بدنية", "jismoniy tayyorgarlik"],
];