// ===========================================================
// SMART TA'LIM — Arab tili 11-qism (Kasb va ish)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR11 = [
  ["مهنة", "kasb"],
  ["وظيفة", "ish (lavozim)"],
  ["طبيب", "shifokor"],
  ["جراح", "jarroh"],
  ["ممرض", "hamshira"],
  ["صيدلي", "farmatsevt"],
  ["معلم", "o'qituvchi"],
  ["مدرس", "muallim"],
  ["أستاذ", "professor"],
  ["مهندس", "muhandis"],
  ["مهندس مدني", "qurilish muhandisi"],
  ["معماري", "arxitektor"],
  ["فني", "texnik mutaxassis"],
  ["كهربائي", "elektrik"],
  ["سباك", "santexnik"],
  ["حداد", "temirchi"],
  ["نجار", "duradgor"],
  ["بنّاء", "bino ustasi"],
  ["عامل", "ishchi"],
  ["مزارع", "dehqon"],
  ["راعي", "cho'pon"],
  ["صياد", "baliqchi"],
  ["خباز", "novvoy"],
  ["حلاق", "sartarosh"],
  ["خياط", "tikuvchi"],
  ["إسكافي", "etikdo'z"],
  ["طباخ", "oshpaz"],
  ["نادل", "ofitsiant"],
  ["بائع", "sotuvchi"],
  ["تاجر", "savdogar"],
  ["محاسب", "buxgalter"],
  ["مصرفي", "bank xodimi"],
  ["مدير", "direktor"],
  ["سكرتير", "kotib"],
  ["محامي", "advokat"],
  ["قاضٍ", "sudya"],
  ["شرطي", "politsiyachi"],
  ["جندي", "askar"],
  ["ضابط", "ofitser"],
  ["رجل إطفاء", "o't o'chiruvchi"],
  ["سائق", "haydovchi"],
  ["طيار", "uchuvchi"],
  ["بحار", "dengizchi"],
  ["رائد فضاء", "kosmonavt"],
  ["عالم", "olim"],
  ["باحث", "tadqiqotchi"],
  ["كاتب", "yozuvchi"],
  ["شاعر", "shoir"],
  ["صحفي", "jurnalist"],
  ["مذيع", "diktor"],
  ["مترجم", "tarjimon"],
  ["مصور", "fotograf"],
  ["رسام", "rassom"],
  ["فنان", "artist"],
  ["مغني", "xonanda"],
  ["ملحن", "bastakor"],
  ["ممثل", "aktyor"],
  ["مخرج", "rejissyor"],
  ["مصمم", "dizayner"],
  ["مطور برمجيات", "dasturchi"],
  ["مبرمج", "dasturchi (koder)"],
  ["خبير", "ekspert"],
  ["مستشار", "maslahatchi"],
  ["رجل أعمال", "tadbirkor"],
  ["مستثمر", "investor"],
  ["اقتصادي", "iqtisodchi"],
  ["صاحب متجر", "do'kon egasi"],
  ["حارس", "qorovul"],
  ["بواب", "darvozabon"],
  ["خادمة", "xizmatkor (farrosh)"],
  ["منظف", "tozalovchi"],
  ["مصفف شعر", "sartarosh (stilist)"],
  ["خبير تجميل", "kosmetolog"],
  ["مدرب", "murabbiy"],
  ["حكم", "hakam (sport)"],
  ["متطوع", "ko'ngilli"],
  ["ممول", "mablag' beruvchi"],
  ["أمين مكتبة", "kutubxonachi"],
  ["موظف", "xodim"],
  ["رئيس", "rahbar"],
  ["وزير", "vazir"],
  ["سفير", "elchi"],
  ["قائد", "sardor"],
  ["زعيم", "yetakchi"],
  ["أستاذ جامعي", "universitet professori"],
  ["نائب", "o'rinbosar"],
  ["عضو", "a'zo"],
  ["شريك", "hamkor"],
  ["صاحب العمل", "ish beruvchi"],
  ["مشغل آلة", "mashina operatori"],
  ["عامل مزرعة", "ferma ishchisi"],
  ["حارس غابات", "o'rmon qorovuli"],
  ["راعي أغنام", "qo'y boquvchi"],
  ["مدرب كرة قدم", "futbol murabbiyi"],
  ["لاعب محترف", "professional o'yinchi"],
  ["رائد أعمال", "biznes asoschisi"],
  ["مستشار قانوني", "huquqiy maslahatchi"],
  ["موزع", "tarqatuvchi"],
  ["تاجر جملة", "ulgurji sotuvchi"],
  ["تاجر تجزئة", "chakana sotuvchi"],
  ["مفتش", "inspektor"],
];