// ===========================================================
// SMART TA'LIM — Arab tili 2-qism (Oila va odamlar)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR2 = [
  ["أب", "ota"],
  ["أم", "ona"],
  ["والد", "ota (valideyn)"],
  ["والدة", "ona (valideyn)"],
  ["أخ", "aka/uka"],
  ["أخت", "opa/singil"],
  ["جد", "bobo"],
  ["جدة", "buvi"],
  ["ابن", "o'g'il"],
  ["ابنة", "qiz (farzand)"],
  ["حفيد", "nabira"],
  ["حفيدة", "nabira (qiz)"],
  ["زوج", "er"],
  ["زوجة", "xotin"],
  ["عريس", "kuyov"],
  ["عروس", "kelin"],
  ["خاطب", "unashtirilgan yigit"],
  ["مخطوبة", "unashtirilgan qiz"],
  ["نسب", "qarindoshlik"],
  ["قريب", "qarindosh"],
  ["عمة", "amma"],
  ["خالة", "xola"],
  ["عم", "amaki"],
  ["خال", "tog'a"],
  ["جار", "qo'shni"],
  ["ضيف", "mehmon"],
  ["مضيف", "mezbon"],
  ["مولود", "yangi tug'ilgan"],
  ["رضيع", "chaqaloq"],
  ["مراهق", "o'smir"],
  ["شاب", "yigit"],
  ["فتاة", "qiz (yoshlikda)"],
  ["شيخ", "oqsoqol"],
  ["عجوز", "keksa (qari)"],
  ["متوفى", "marhum"],
  ["يتيم", "yetim"],
  ["أرملة", "beva"],
  ["ولادة", "tug'ilish"],
  ["ميلاد", "tug'ilgan kun"],
  ["زفاف", "to'y"],
  ["حفلة", "ziyofat"],
  ["هدية", "sovg'a"],
  ["عيد ميلاد", "tug'ilgan kun bayrami"],
  ["زواج", "nikoh"],
  ["طلاق", "ajralish"],
  ["عقد زواج", "nikoh shartnomasi"],
  ["مهر", "mahr/to'y puli"],
  ["عناق", "quchoqlash"],
  ["قبلة", "o'pish"],
  ["مصافحة", "qo'l berish"],
  ["سلام", "salom"],
  ["عائلة كبيرة", "katta oila"],
  ["عائلة صغيرة", "kichik oila"],
  ["أحفاد", "nabiralar"],
  ["أجداد", "bobolar"],
  ["آباء", "otalar"],
  ["أمهات", "onalar"],
  ["أطفال", "bolalar"],
  ["شباب", "yoshlar"],
  ["كبار السن", "keksalar"],
  ["رجولة", "erkaklik"],
  ["أنوثة", "ayollik"],
  ["أخوة", "birodarlik"],
  ["صداقة", "do'stlik"],
  ["احترام", "hurmat"],
  ["حنان", "mehr"],
  ["رعاية", "g'amxo'rlik"],
  ["تربية", "tarbiya"],
  ["عائلة", "oila"],
  ["بيت العائلة", "ota uyi"],
  ["نسل", "avlod"],
  ["جيل", "avlod (nasl)"],
  ["معاصر", "zamondosh"],
  ["توأم", "egizak"],
  ["ابن عم", "amakivachcha (erkak)"],
  ["ابنة عم", "amakivachcha (qiz)"],
  ["ابن خال", "tog'avachcha (erkak)"],
  ["ابنة خال", "tog'avachcha (qiz)"],
  ["عرس", "to'y (marosim)"],
  ["عزاء", "ta'ziya"],
  ["إخوة", "birodarlar"],
  ["ربة البيت", "uy bekasi"],
  ["رب الأسرة", "oila boshlig'i"],
  ["ابن وحيد", "yolg'iz o'g'il"],
  ["الابن الأكبر", "to'ng'ich o'g'il"],
  ["الأخت الصغرى", "kenja singil"],
  ["صهر", "kuyov (qizning eri)"],
  ["كنة", "kelin (o'g'ilnigi)"],
  ["أخ غير شقيق", "o'gay aka/uka"],
  ["أخت غير شقيقة", "o'gay opa/singil"],
  ["تعارف", "tanishuv"],
  ["مودة", "do'stona munosabat"],
  ["محبة", "muhabbat"],
  ["وفاء", "vafo/sadoqat"],
  ["ود", "mehr-muhabbat"],
  ["أسرة", "oilaviy doira"],
  ["قرابة", "qarindoshlik aloqasi"],
  ["وليد", "chaqaloq (erkak)"],
  ["مولدة", "doya"],
  ["أسرة كريمة", "ulug' oila"],
  ["بنت صغرى", "kenja qiz"],
];