// ===========================================================
// SMART TA'LIM — Arab tili 8-qism (Kiyim-kechak)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR8 = [
  ["ملابس", "kiyimlar"],
  ["ثياب", "kiyim"],
  ["زي", "libos/uniforma"],
  ["فستان", "ko'ylak (ayollar)"],
  ["قميص", "ko'ylak (erkaklar)"],
  ["بنطال", "shim"],
  ["جينز", "jinsi"],
  ["شورت", "shorti"],
  ["تنورة", "yubka"],
  ["بلوزة", "bluzka"],
  ["تي شيرت", "mayka"],
  ["كنزة صوف", "jun kofta"],
  ["سترة", "kurtka"],
  ["معطف", "palto"],
  ["معطف واق من المطر", "yomg'ir paltosi"],
  ["بدلة", "kostyum"],
  ["ربطة عنق", "galstuk"],
  ["صدرية", "yelek"],
  ["بيجامة", "piyama"],
  ["قميص نوم", "tungi ko'ylak"],
  ["روب", "xalat"],
  ["ملابس داخلية", "ichki kiyim"],
  ["جوارب", "paypoqlar"],
  ["جورب", "paypoq (bitta)"],
  ["حزام", "kamar"],
  ["وشاح", "sharf"],
  ["قفازات", "qo'lqoplar"],
  ["قبعة", "qalpoq/shlyapa"],
  ["كاب", "kepka"],
  ["طاقية", "doppi"],
  ["عمامة", "salla"],
  ["حجاب", "hijob"],
  ["خمار", "ro'mol"],
  ["نقاب", "niqob (yuzchini)"],
  ["عباءة", "abaya (chopon)"],
  ["جلباب", "jilob"],
  ["فستان زفاف", "kelinlik ko'ylagi"],
  ["بدلة رسمية", "rasmiy kostyum"],
  ["ملابس رياضية", "sport kiyimi"],
  ["حذاء", "poyafzal"],
  ["حذاء رياضي", "krossovka"],
  ["جزمة", "etik"],
  ["صندل", "sandal"],
  ["شبشب", "shippak"],
  ["خف", "to'piqcha"],
  ["كعب عالٍ", "baland poshna"],
  ["نعل", "taglik (nayl)"],
  ["رباط حذاء", "bog'ich"],
  ["قماش", "mato"],
  ["قطن", "paxta"],
  ["حرير", "ipak"],
  ["صوف", "jun"],
  ["جلد", "charm"],
  ["زر", "tugma"],
  ["سحاب", "zamok"],
  ["جيب", "cho'ntak"],
  ["ياقة", "yoqa"],
  ["كم", "yeng"],
  ["حاشية", "etag"],
  ["بطانة", "astar"],
  ["غيار", "kiyim almashtirish"],
  ["قياس", "o'lcham"],
  ["مقاس", "razmer"],
  ["مقاس صغير", "kichik razmer"],
  ["مقاس كبير", "katta razmer"],
  ["مقاس متوسط", "o'rta razmer"],
  ["عارضة أزياء", "model (ayol)"],
  ["مصمم أزياء", "dizayner"],
  ["موضة", "moda"],
  ["أنيق", "nafis/chiroyli"],
  ["واسع", "keng"],
  ["ضيق", "tor"],
  ["قصير", "kalta"],
  ["طويل", "uzun"],
  ["مريح", "qulay"],
  ["جديد", "yangi"],
  ["مستعمل", "ishlatilgan"],
  ["نظيف", "toza"],
  ["متسخ", "iflos"],
  ["مكوي", "dazmollangan"],
  ["مجعد", "g'ijimlangan"],
  ["متجر ملابس", "kiyim do'koni"],
  ["غرفة تغيير", "kiyinish xonasi"],
  ["مرآة كاملة", "to'liq bo'y oynasi"],
  ["شماعة", "ilgich"],
  ["عطر", "atir"],
  ["مساحيق تجميل", "kosmetika"],
  ["مكياج", "make-up"],
  ["أحمر شفاه", "lab bo'yog'i"],
  ["عقد", "marjon"],
  ["خاتم", "uzuk"],
  ["سوار", "bilaguzuk"],
  ["أقراط", "sirg'alar"],
  ["ساعة يد", "qo'l soati"],
  ["نظارة", "ko'zoynak"],
  ["محفظة", "hamyon"],
  ["حقيبة يد", "qo'l sumkasi"],
  ["حقيبة ظهر", "ryukzak"],
  ["مشط", "taroq"],
  ["فرشاة", "cho'tka"],
  ["حذاء جلدي", "charm poyafzal"],
  ["صنادل صيفية", "yozgi sandallar"],
  ["لباس", "libos"],
];