// ===========================================================
// SMART TA'LIM — Arab tili 4-qism (Raqamlar va vaqt)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR4 = [
  ["صفر", "nol"],
  ["واحد", "bir"],
  ["اثنان", "ikki"],
  ["ثلاثة", "uch"],
  ["أربعة", "to'rt"],
  ["خمسة", "besh"],
  ["ستة", "olti"],
  ["سبعة", "yetti"],
  ["ثمانية", "sakkiz"],
  ["تسعة", "to'qqiz"],
  ["عشرة", "o'n"],
  ["أحد عشر", "o'n bir"],
  ["اثنا عشر", "o'n ikki"],
  ["ثلاثة عشر", "o'n uch"],
  ["أربعة عشر", "o'n to'rt"],
  ["خمسة عشر", "o'n besh"],
  ["عشرون", "yigirma"],
  ["واحد وعشرون", "yigirma bir"],
  ["ثلاثون", "o'ttiz"],
  ["أربعون", "qirq"],
  ["خمسون", "ellik"],
  ["ستون", "oltmish"],
  ["سبعون", "yetmish"],
  ["ثمانون", "sakson"],
  ["تسعون", "to'qson"],
  ["مائة", "yuz"],
  ["ألف", "ming"],
  ["مليون", "million"],
  ["مليار", "milliard"],
  ["زوج", "juft"],
  ["فرد", "toq"],
  ["نصف", "yarim"],
  ["ربع", "chorak"],
  ["ثلث", "uchdan bir"],
  ["مزدوج", "ikki barobar"],
  ["عدد", "son"],
  ["رقم", "raqam"],
  ["مرة", "marta"],
  ["مرتان", "ikki marta"],
  ["ثلاث مرات", "uch marta"],
  ["أول", "birinchi"],
  ["ثانٍ", "ikkinchi"],
  ["ثالث", "uchinchi"],
  ["رابع", "to'rtinchi"],
  ["خامس", "beshinchi"],
  ["ترتيب", "tartib"],

  // Vaqt
  ["وقت", "vaqt"],
  ["لحظة", "lahza"],
  ["دقيقة", "daqiqa"],
  ["ساعة", "soat"],
  ["ثانية", "soniya"],
  ["يوم", "kun"],
  ["أسبوع", "hafta"],
  ["شهر", "oy"],
  ["سنة", "yil"],
  ["عقد", "o'n yillik"],
  ["قرن", "asr"],
  ["تاريخ", "sana"],
  ["اليوم", "bugun"],
  ["غدا", "ertaga"],
  ["أمس", "kecha"],
  ["الآن", "hozir"],
  ["صباحا", "ertalab"],
  ["ظهرا", "peshin"],
  ["مساء", "kechqurun"],
  ["ليلا", "tunda"],
  ["فجرا", "saharda"],
  ["موعد", "uchrashuv vaqti"],
  ["تأخير", "kechikish"],
  ["مبكرا", "erta"],
  ["متأخرا", "kech"],
  ["دائم", "doimiy"],
  ["مؤقت", "vaqtinchalik"],
  ["أبدي", "abadiy"],
  ["قديم", "qadimiy"],
  ["حديث", "zamonaviy"],
  ["مستقبل", "kelajak"],
  ["حاضر", "hozirgi"],
  ["ماضٍ", "o'tmish"],
  ["أسبوعيا", "haftalik"],
  ["شهريا", "oylik"],
  ["سنويا", "yillik"],
  ["يوميا", "kunlik"],
  ["تقويم", "taqvim"],
  ["فصل من السنة", "yil fasli"],
  ["ربيع", "bahor"],
  ["صيف", "yoz"],
  ["خريف", "kuz"],
  ["شتاء", "qish"],
  ["مدة", "muddat"],
  ["مرحلة", "bosqich"],
  ["فترة", "davr"],
  ["عصر", "asr/davr"],
  ["جيل", "avlod"],
  ["فورا", "darhol"],
  ["دائما", "doim"],
  ["أحيانا", "ba'zan"],
  ["نادرا", "kamdan-kam"],
  ["كثيرا", "ko'p (tez-tez)"],
  ["قليلا", "oz (kam)"],
  ["في الحال", "shu zahotiyoq"],
  ["لاحقا", "keyinroq"],
  ["سابقا", "avvalroq"],
];