// ===========================================================
// SMART TA'LIM — Lug'at 7-qism (Kasb va ish)
// Format: [inglizcha, o'zbekcha]
// ===========================================================

const LUGAT_JOB = [
  // Kasblar
  ["doctor", "shifokor"],
  ["teacher", "o'qituvchi"],
  ["engineer", "muhandis"],
  ["lawyer", "advokat"],
  ["architect", "arxitektor"],
  ["scientist", "olim"],
  ["writer", "yozuvchi"],
  ["journalist", "jurnalist"],
  ["artist", "rassom"],
  ["musician", "musiqachi"],
  ["singer", "xonanda"],
  ["actor", "aktyor"],
  ["dancer", "raqqos/raqqosa"],
  ["actor", "dramaturg"],
  ["director", "rejissyor"],
  ["photographer", "fotograf"],
  ["cook", "oshpaz"],
  ["waiter", "ofitsiant"],
  ["driver", "haydovchi"],
  ["pilot", "uchuvchi"],
  ["sailor", "dengizchi"],
  ["soldier", "askar"],
  ["policeman", "politsiyachi"],
  ["firefighter", "o't o'chiruvchi"],
  ["farmer", "dehqon"],
  ["herdsman", "cho'pon"],
  ["carpenter", "duradgor"],
  ["blacksmith", "temirchi"],
  ["tailor", "tikuvchi"],
  ["shoemaker", "etikdo'z"],
  ["baker", "novvoy"],
  ["butcher", "qassob"],
  ["grocer", "baqqol"],
  ["trader", "savdogar"],
  ["salesman", "sotuvchi"],
  ["cashier", "kassir"],
  ["accountant", "buxgalter"],
  ["banker", "bank xodimi"],
  ["manager", "menejer"],
  ["businessman", "tadbirkor"],
  ["secretary", "kotiba"],
  ["translator", "tarjimon"],
  ["interpreter", "tilmoch"],
  ["librarian", "kutubxonachi"],
  ["nurse", "hamshira"],
  ["dentist", "stomatolog"],
  ["pharmacist", "farmatsevt"],
  ["veterinarian", "veterinariya vrachi"],
  ["electrician", "elektrik"],
  ["plumber", "santexnik"],

  // Ish mavzusi
  ["job", "ish/hunar"],
  ["work", "ish"],
  ["career", "karrera"],
  ["salary", "maosh"],
  ["wage", "haq to'lash"],
  ["income", "daromad"],
  ["office", "ofis"],
  ["factory", "zavod"],
  ["company", "kompaniya"],
  ["business", "biznes"],
  ["employer", "ish beruvchi"],
  ["employee", "xodim"],
  ["colleague", "hamkasab"],
  ["boss", "boshliq"],
  ["client", "mijoz"],
  ["customer", "xaridor"],
  ["meeting", "yig'ilish"],
  ["interview", "suhbat"],
  ["experience", "tajriba"],
  ["skill", "malaka/ko'nikma"],

  // Ish joyi vositalari
  ["computer", "kompyuter"],
  ["printer", "printer"],
  ["document", "hujjat"],
  ["file", "fayl"],
  ["folder", "papka"],
  ["report", "hisobot"],
  ["schedule", "jadval"],
  ["deadline", "muddat"],
  ["task", "topshiriq"],
  ["project", "loyiha"],
  ["team", "jamoa"],
  ["uniform", "forma"],
  ["badge", "badge/ko'krak nishoni"],
  ["business card", "tashrif qog'ozi"],
  ["briefcase", "dokumentsumka"],
  ["laptop", "noutbuk"],
  ["notebook", "daftar"],
  ["stapler", "stepler"],
  ["scissors", "qaychi"],
  ["calculator", "kalkulyator"],
];