// ===========================================================
// SMART TA'LIM — Lug'at 10-qism (Tabiat va atrof-muhit)
// Format: [inglizcha, o'zbekcha]
// ===========================================================

const LUGAT_NATURE = [
  // Tabiat hodisalari
  ["weather", "ob-havo"],
  ["sun", "quyosh"],
  ["moon", "oy"],
  ["star", "yulduz"],
  ["sky", "osmon"],
  ["cloud", "bulut"],
  ["rain", "yomg'ir"],
  ["snow", "qor"],
  ["wind", "shamol"],
  ["storm", "bo'ron"],
  ["thunder", "momaqaldiroq"],
  ["lightning", "chaqmoq"],
  ["rainbow", "kamalak"],
  ["fog", "tuman"],
  ["frost", "ayoz"],
  ["hail", "do'l"],
  ["dew", "shabnam"],
  ["ice", "muz"],
  ["heat", "issiqlik"],
  ["drought", "qurg'oqchilik"],

  // Suv va yer shakllari
  ["sea", "dengiz"],
  ["ocean", "okean"],
  ["river", "daryo"],
  ["lake", "ko'l"],
  ["spring", "buloq"],
  ["waterfall", "sharshara"],
  ["mountain", "tog'"],
  ["hill", "tepalik"],
  ["valley", "vodiy"],
  ["desert", "cho'l"],
  ["forest", "o'rmon"],
  ["jungle", "tropik o'rmon"],
  ["plain", "tekislik"],
  ["island", "orol"],
  ["peninsula", "yarim orol"],
  ["bay", "ko'rfaza"],
  ["beach", "plyaj"],
  ["cave", "g'or"],
  ["volcano", "vulkan"],
  ["glacier", "muzlik"],

  // O'simliklar
  ["tree", "daraxt"],
  ["oak", "eman daraxti"],
  ["pine", "qarag'ay"],
  ["poplar", "terak"],
  ["willow", "tol"],
  ["fruit tree", "mevali daraxt"],
  ["branch", "shox"],
  ["leaf", "barg"],
  ["root", "ildiz"],
  ["trunk", "tana"],
  ["seed", "urug'"],
  ["bud", "kurtak"],
  ["flower", "gul"],
  ["rose", "atirgul"],
  ["tulip", "lola"],
  ["grass", "o't"],
  ["reed", "qamish"],
  ["moss", "yo'sin"],
  ["fern", "paporotnik"],
  ["nettle", "gazanda"],

  // Hayvonot dunyosi
  ["animal", "hayvon"],
  ["bird", "qush"],
  ["fish", "baliq"],
  ["insect", "hasharot"],
  ["dog", "it"],
  ["cat", "mushuk"],
  ["horse", "ot"],
  ["cow", "sigir"],
  ["sheep", "qo'y"],
  ["goat", "echki"],
  ["wolf", "bo'ri"],
  ["fox", "tulki"],
  ["bear", "ayiq"],
  ["lion", "sher"],
  ["tiger", "yo'lbars"],
  ["elephant", "fil"],
  ["camel", "tuya"],
  ["snake", "ilon"],
  ["spider", "o'rgimchak"],
  ["bee", "asalari"],

  // Atrof-muhit
  ["environment", "atrof-muhit"],
  ["ecology", "ekologiya"],
  ["nature", "tabiat"],
  ["pollution", "ifloslanish"],
  ["waste", "chiqindi"],
  ["garbage", "axlat"],
  ["recycling", "qayta ishlash"],
  ["clean", "toza"],
  ["dirty", "iflos"],
  ["fresh air", "toza havo"],
  ["oil spill", "neft to'kilishi"],
  ["greenhouse", "issiqxona"],
  ["climate", "iqlim"],
  ["climate change", "iqlim o'zgarishi"],
  ["global warming", "global isish"],
  ["sun energy", "quyosh energiyasi"],
  ["water conservation", "suvni tejash"],
  ["protection", "muhofaza"],
  ["preserve", "asrash"],
  ["sustainable", "barqaror"],
];