// ===========================================================
// SMART TA'LIM — Lug'at 1-qism
// Format: [inglizcha, o'zbekcha]
// Yangi so'z qo'shish uchun quyidagi jadvalga qator yozing.
// ===========================================================

const LUGAT_OSON = [
  // Oila va odamlar
  ["family", "oila"],
  ["mother", "ona"],
  ["father", "ota"],
  ["brother", "aka/uka"],
  ["sister", "opa/singil"],
  ["friend", "do'st"],
  ["child", "bola"],
  ["teacher", "o'qituvchi"],
  ["student", "talaba/o'quvchi"],
  ["neighbor", "qo'shni"],

  // Ta'lim
  ["school", "maktab"],
  ["university", "universitet"],
  ["book", "kitob"],
  ["lesson", "dars"],
  ["homework", "uy vazifasi"],
  ["exam", "imtihon"],
  ["knowledge", "bilim"],
  ["library", "kutubxona"],
  ["notebook", "daftar"],
  ["pen", "ruchka"],
  ["pencil", "qalam"],
  ["classroom", "sinf xonasi"],
  ["question", "savol"],
  ["answer", "javob"],
  ["grade", "baho"],
  ["degree", "diplom/daraja"],
  ["scholarship", "stipendiya"],
  ["lecture", "ma'ruza"],
  ["research", "tadqiqot"],
  ["science", "fan"],

  // Kundalik hayot
  ["house", "uy"],
  ["food", "ovqat"],
  ["water", "suv"],
  ["bread", "non"],
  ["tea", "choy"],
  ["morning", "ertalab"],
  ["evening", "kechqurun"],
  ["night", "tun"],
  ["day", "kun"],
  ["week", "hafta"],
  ["month", "oy"],
  ["year", "yil"],
  ["time", "vaqt"],
  ["work", "ish"],
  ["money", "pul"],
  ["city", "shahar"],
  ["village", "qishloq"],
  ["street", "ko'cha"],
  ["car", "mashina"],
  ["road", "yo'l"],

  // Fe'llar
  ["to read", "o'qimoq"],
  ["to write", "yozmoq"],
  ["to speak", "gapirmoq"],
  ["to listen", "eshitmoq"],
  ["to understand", "tushunmoq"],
  ["to learn", "o'rganmoq"],
  ["to teach", "o'qitmoq"],
  ["to go", "bormoq"],
  ["to come", "kelmoq"],
  ["to eat", "yemoq"],
  ["to drink", "ichmoq"],
  ["to sleep", "uxlamoq"],
  ["to work", "ishlamoq"],
  ["to help", "yordam bermoq"],
  ["to think", "o'ylamoq"],
  ["to know", "bilmoq"],
  ["to want", "xohlamoq"],
  ["to love", "sevmoq"],
  ["to live", "yashamoq"],
  ["to buy", "sotib olmoq"],

  // Sifatlar
  ["good", "yaxshi"],
  ["bad", "yomon"],
  ["big", "katta"],
  ["small", "kichik"],
  ["new", "yangi"],
  ["old", "eski"],
  ["beautiful", "chiroyli"],
  ["difficult", "qiyin"],
  ["easy", "oson"],
  ["fast", "tez"],
  ["slow", "sekin"],
  ["important", "muhim"],
  ["interesting", "qiziqarli"],
  ["happy", "baxtli"],
  ["strong", "kuchli"],

  // Vaqt va sonlar
  ["today", "bugun"],
  ["tomorrow", "ertaga"],
  ["yesterday", "kecha"],
  ["now", "hozir"],
  ["always", "doim"],
  ["never", "hech qachon"],
  ["one", "bir"],
  ["two", "ikki"],
  ["three", "uch"],
  ["ten", "o'n"],
  ["hundred", "yuz"],
  ["thousand", "ming"],

  // Tabiat
  ["sun", "quyosh"],
  ["moon", "oy (osmon)"],
  ["star", "yulduz"],
  ["sky", "osmon"],
  ["earth", "yer"],
  ["mountain", "tog'"],
  ["river", "daryo"],
  ["sea", "dengiz"],
  ["tree", "daraxt"],
  ["flower", "gul"],
  ["rain", "yomg'ir"],
  ["snow", "qor"],
  ["wind", "shamol"],
  ["weather", "ob-havo"],

  // Texnologiya
  ["computer", "kompyuter"],
  ["phone", "telefon"],
  ["internet", "internet"],
  ["video", "video"],
  ["application", "ilova"],
  ["password", "parol"],
  ["message", "xabar"],
  ["screen", "ekran"],

  // His-tuyg'u
  ["happiness", "baxt"],
  ["sadness", "qayg'u"],
  ["fear", "qo'rquv"],
  ["hope", "umid"],
  ["dream", "orzu"],
  ["success", "muvaffaqiyat"],
  ["effort", "harakat"],
  ["patience", "sabr"],
];
