// ===========================================================
// SMART TA'LIM — Lug'at 12-qism (Hissiyot va muloqot)
// Format: [inglizcha, o'zbekcha]
// ===========================================================

const LUGAT_EMOTIONS = [
  // Ijobiy his-tuyg'ular
  ["happiness", "baxt"],
  ["joy", "shodlik"],
  ["love", "sevgi"],
  ["kindness", "mehr"],
  ["trust", "ishonch"],
  ["respect", "hurmat"],
  ["hope", "umid"],
  ["dream", "orzu"],
  ["courage", "jasurlik"],
  ["confidence", "ishonch (o'ziga)"],
  ["pride", "faxr"],
  ["gratitude", "minnatdorlik"],
  ["sympathy", "hamdardlik"],
  ["enthusiasm", "ish-tibiyos"],
  ["curiosity", "qiziquvchanlik"],
  ["peace", "tinchlik"],
  ["pleasure", "zavq"],
  ["comfort", "farovonlik"],
  ["surprise", "hayrat"],
  ["excitement", "hayajon (qiziqish)"],

  // Salbiy his-tuyg'ular
  ["sadness", "qayg'u"],
  ["anger", "g'azab"],
  ["fear", "qo'rquv"],
  ["worry", "xavotirlanish"],
  ["anxiety", "bezovtalik"],
  ["jealousy", "hasad"],
  ["envy", "rashk/hasad"],
  ["hate", "nafrat"],
  ["shame", "uyat"],
  ["guilt", "ayb"],
  ["regret", "afsus"],
  ["disappointment", "umidsizlik"],
  ["loneliness", "yolg'izlik"],
  ["boredom", "zerikish"],
  ["tiredness", "charchoq"],
  ["pain", "azob"],
  ["sorrow", "musibat"],
  ["frustration", "g'ashlik"],
  ["doubt", "shubha"],
  ["embarrassment", "xijolat"],

  // Muloqot va munosabat
  ["friend", "do'st"],
  ["friendship", "do'stlik"],
  ["enemy", "dushman"],
  ["family", "oila"],
  ["relative", "qarindosh"],
  ["neighbor", "qo'shni"],
  ["guest", "mehmon"],
  ["host", "mezbon"],
  ["partner", "sherik"],
  ["marriage", "nikoh"],
  ["engagement", "kelinlik/fotih"],
  ["wedding", "to'y"],
  ["congratulations", "tabriklar"],
  ["birthday", "tug'ilgan kun"],
  ["holiday", "bayram"],
  ["celebration", "tantana"],
  ["gift", "sovg'a"],
  ["invitation", "taklif"],
  ["apology", "uzr"],
  ["promise", "va'da"],

  // Muloqot fe'llari
  ["to smile", "kulimsimoq"],
  ["to laugh", "kulmoq"],
  ["to cry", "yig'lamoq"],
  ["to shout", "baqirmoq"],
  ["to whisper", "shivirlamoq"],
  ["to greet", "salomlashmoq"],
  ["to introduce", "tanishtirmoq"],
  ["to praise", "maqtamoq"],
  ["to blame", "ayblamoq"],
  ["to forgive", "kechirmoq"],
  ["to thank", "minnatdorchilik bildirmoq"],
  ["to help", "yordam bermoq"],
  ["to comfort", "ovutmoq"],
  ["to encourage", "rag'batlantirmoq"],
  ["to disagree", "qarshilik bildirmoq"],
  ["to argue", "bahslashmoq"],
  ["to discuss", "muhokama qilmoq"],
  ["to agree", "rozi bo'lmoq"],
  ["to support", "qo'llab-quvvatlamoq"],
  ["to listen", "tinglamoq"],
];