// ===========================================================
// SMART TA'LIM — Arab tili 15-qism (Hissiyot va sifatlar)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR15 = [
  // Hissiyotlar
  ["سعادة", "baxt"],
  ["حزن", "qayg'u"],
  ["غضب", "g'azab"],
  ["خوف", "qo'rquv"],
  ["قلق", "xavotir"],
  ["راحة", "taskin/rohat"],
  ["تعب", "charchoq"],
  ["يأس", "umidsizlik"],
  ["أمل", "umid"],
  ["حب", "muhabbat"],
  ["بغض", "nafrat"],
  ["شوق", "intizorlik"],
  ["وحدة", "yolg'izlik"],
  ["صبر", "sabr"],
  ["شكر", "minnatdorlik"],
  ["إعجاب", "hayrat"],
  ["دهشة", "ajablanish"],
  ["ذهول", "hayrat (qattiq)"],
  ["إحراج", "xijolat"],
  ["خجل", "uyatchanlik"],
  ["فخر", "g'urur"],
  ["تواضع", "kamtarlik"],
  ["غرور", "takabburlik"],
  ["حسد", "hasad"],
  ["غيرة", "rashk"],
  ["شجاعة", "jasurlik"],
  ["جبن", "qo'rqoqlik"],
  ["لطف", "muloyimlik"],
  ["قسوة", "qattiqqo'llik"],
  ["لين", "yumshoqlik"],
  ["وقاحة", "andishasizlik"],
  ["أدب", "odob"],
  ["هدوء", "tinchlik"],
  ["صخب", "shovqin"],
  ["سكينة", "sokinlik"],
  ["طمأنينة", "xotirjamlik"],
  ["اشتياق", "sog'inch"],
  ["رضا", "rozilik"],
  ["ندم", "afsus"],
  ["أسف", "pushaymonlik"],
  ["عتاب", "tanbeh"],
  ["اتهام", "ayblash"],
  ["عفو", "kechirim"],
  ["تسامح", "bag'rikenglik"],
  ["مودة", "do'stona munosabat"],
  ["انشراح", "xursandchilik"],
  ["انبساط", "quvonch (yuzda)"],
  ["طرب", "zavq (musiqada)"],
  ["تأثر", "ta'sirlanish"],
  ["حماس", "ishtiyoq"],
  ["فتور", "sustkashlik"],
  ["كسل", "dangasalik"],
  ["نشاط", "faollik"],
  ["اجتهاد", "tirishqoqlik"],
  ["إهمال", "beparvolik"],
  ["دقة", "aniqlik"],
  ["إتقان", "ustalik"],

  // Sifatlar
  ["كبير", "katta"],
  ["صغير", "kichik"],
  ["طويل", "uzun"],
  ["قصير", "kalta/past"],
  ["واسع", "keng"],
  ["ضيق", "tor"],
  ["سمين", "semiz"],
  ["نحيف", "ozg'in"],
  ["قوي", "kuchli"],
  ["ضعيف", "kuchsiz"],
  ["سريع", "tez"],
  ["بطيء", "sekin"],
  ["نظيف", "toza"],
  ["قذر", "iflos"],
  ["ساخن", "issiq"],
  ["بارد", "sovuq"],
  ["حار", "qaynoq"],
  ["غالي", "qimmat"],
  ["رخيص", "arzon"],
  ["جميل", "chiroyli"],
  ["قبيح", "xunuk"],
  ["صحيح", "to'g'ri"],
  ["خاطئ", "xato"],
  ["جديد", "yangi"],
  ["قديم", "eski"],
  ["صعب", "qiyin"],
  ["سهل", "oson"],
  ["مهم", "muhim"],
  ["ثانوي", "ikkinchi darajali"],
  ["أساسي", "asosiy"],
  ["عام", "umumiy"],
  ["خاص", "xususiy"],
  ["غريب", "g'alati/begona"],
  ["مألوف", "tanish"],
  ["لذيذ", "mazali"],
  ["مرّ", "achchiq"],
  ["حلو", "shirin"],
  ["مالح", "sho'r"],
  ["حامض", "nordon"],
  ["عجيب", "ajoyib (g'alati)"],
  ["رائع", "ajoyib"],
  ["ممتاز", "a'lo"],
  ["جيد", "yaxshi"],
  ["سيئ", "yomon"],
  ["عادل", "adolatli"],
  ["ظالم", "zolim"],
  ["كريم", "saxovatli"],
  ["بخيل", "xasis"],
  ["صادق", "rostgo'y"],
  ["كاذب", "yolg'onchi"],
  ["مشهور", "mashhur"],
  ["مجهول", "noma'lum"],
  ["ممتلئ", "to'lgan"],
  ["فارغ", "bo'sh"],
  ["مغلق", "yopiq"],
  ["مفتوح", "ochiq"],
  ["ناعم", "yumshoq"],
  ["خشن", "qo'pol"],
  ["خالٍ", "xoli (bo'sh)"],
  ["جميل المنظر", "ko'rinishi go'zal"],
  ["بسيط", "sodda"],
  ["معقد", "murakkab"],
  ["واضح", "aniq (ravshan)"],
  ["غامض", "noaniq"],
  ["مفيد", "foydali"],
  ["ضار", "zararli"],
  ["آمن", "xavfsiz"],
  ["خطير", "xavfli"],
  ["سعيد", "baxtli"],
  ["حزين", "g'amgin"],
  ["غاضب", "g'azablangan"],
  ["خائف", "qo'rqqan"],
  ["مثقف", "o'qimishli"],
  ["جاهل", "o'qimagan"],
  ["ذكي", "aqlli"],
  ["غبي", "ahmoq"],
  ["محترم", "hurmatli"],
  ["مستخدم", "ishlatilgan"],
];