// ===========================================================
// SMART TA'LIM — Lug'at 8-qism (Sport va dam olish)
// Format: [inglizcha, o'zbekcha]
// ===========================================================

const LUGAT_SPORT = [
  // Sport turlari
  ["football", "futbol"],
  ["soccer", "futbol (amerika)"],
  ["basketball", "basketbol"],
  ["volleyball", "voleybol"],
  ["tennis", "tennis"],
  ["table tennis", "stol tennisi"],
  ["boxing", "boks"],
  ["wrestling", "kurash"],
  ["judo", "dzyudo"],
  ["karate", "karate"],
  ["swimming", "suzish"],
  ["running", "yugurish"],
  ["jogging", "yengil yugurish"],
  ["cycling", "velosport"],
  ["horse riding", "ot minish"],
  ["skiing", "chang'i sporti"],
  ["skating", "konkida uchish"],
  ["gymnastics", "gimnastika"],
  ["athletics", "yengil atletika"],
  ["weightlifting", "og'ir atletika"],
  ["hockey", "xokkey"],
  ["golf", "golf"],
  ["rugby", "regbi"],
  ["baseball", "beysbol"],
  ["cricket", "kriket"],
  ["badminton", "badminton"],
  ["archery", "kamondan otish"],
  ["fencing", "qilichbozlik"],
  ["chess", "shaxmat"],
  ["checkers", "shashka"],

  // Sport buyumlari va jihozlar
  ["ball", "to'p"],
  ["goal", "gol/darvoza"],
  ["net", "to'r"],
  ["racket", "raketka"],
  ["glove", "qo'lqop"],
  ["helmet", "dubulg'a"],
  ["whistle", "hushtak"],
  ["trophy", "kubok"],
  ["medal", "medal"],
  ["cup", "chempionat kubogi"],
  ["team", "jamoa"],
  ["coach", "murabbiy"],
  ["player", "o'yinchi"],
  ["referee", "hakam"],
  ["spectator", "tomoshabin"],
  ["stadium", "stadion"],
  ["gym", "sport zal"],
  ["pool", "basseyn"],
  ["field", "maydon"],
  ["court", "kort/maydoncha"],

  // O'yin va musobaqa so'zlari
  ["game", "o'yin"],
  ["match", "o'yin (musobaqa)"],
  ["competition", "musobaqa"],
  ["tournament", "turnir"],
  ["championship", "chempionat"],
  ["winner", "g'olib"],
  ["loser", "mag'lub"],
  ["draw", "durang"],
  ["score", "hisob"],
  ["point", "ochko"],
  ["record", "rekord"],
  ["training", "mashg'ulot"],
  ["practice", "amaliyot"],
  ["warm-up", "isitish"],
  ["strength", "kuch"],
  ["speed", "tezlik"],
  ["agility", "chaqqonlik"],
  ["victory", "g'alaba"],
  ["defeat", "mag'lubiyat"],
  ["fair play", "halol o'yin"],

  // Dam olish va hobbilar
  ["hobby", "sevimli mashg'ulot"],
  ["music", "musiqa"],
  ["dancing", "raqs"],
  ["reading", "kitob o'qish"],
  ["painting", "rasm chizish"],
  ["drawing", "chizish"],
  ["photography", "fotosuratga olish"],
  ["fishing", "baliq ovlash"],
  ["hunting", "ov qilish"],
  ["camping", "lager"],
  ["picnic", "sayr"],
  ["traveling", "sayohat qilish"],
  ["gardening", "bog'bonlik"],
  ["cooking", "ovqat pishirish"],
  ["sewing", "tikuvchilik"],
  ["knitting", "to'qish"],
  ["collecting", "yig'ish/kolleksiya"],
  ["flying kite", "varrak uchirish"],
  ["playing cards", "karta o'ynash"],
  ["movie", "kino"],
];