// ===========================================================
// SMART TA'LIM — Arab tili 7-qism (Uy va jihozlar)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR7 = [
  ["مسكن", "turar joy"],
  ["عقار", "ko'chmas mulk"],
  ["إيجار", "ijara"],
  ["مستأجر", "ijarachi"],
  ["صاحب البيت", "uy egasi"],
  ["غرفة", "xona"],
  ["مطبخ", "oshxona"],
  ["صالون", "salon"],
  ["غرفة استقبال", "mehmonxona"],
  ["غرفة نوم", "yotoqxona"],
  ["حمام", "hammom"],
  ["دورة مياه", "hojatxona"],
  ["ممر", "koridor"],
  ["شرفة", "balkon"],
  ["سطح", "tom (terasa)"],
  ["سقف", "ship"],
  ["جدار", "devor"],
  ["أرض", "pol"],
  ["سجاد", "gilam"],
  ["فرش", "pastki gilam"],
  ["نافذة", "deraza"],
  ["باب", "eshik"],
  ["قفل", "qulf"],
  ["مفتاح", "kalit"],
  ["زجاج", "shisha (oyna)"],
  ["سلم", "zinapoya"],
  ["مصعد", "lift"],
  ["غرفة المعيشة", "yashash xonasi"],
  ["أثاث", "mebel"],
  ["طاولة", "stol"],
  ["كرسي", "stul"],
  ["مقعد", "o'rindiq"],
  ["أريكة", "divan"],
  ["كنبة", "kreslo"],
  ["سرير", "karavot"],
  ["فراش", "matras"],
  ["وسادة", "yostiq"],
  ["لحاف", "ko'rpa"],
  ["بطانية", "adyol"],
  ["خزانة", "shkaf"],
  ["خزانة ملابس", "garderob"],
  ["رف", "tokcha"],
  ["مكتب", "yozuv stoli"],
  ["حاسوب", "kompyuter"],
  ["تلفاز", "televizor"],
  ["مكيف", "konditsioner"],
  ["مروحة", "ventilyator"],
  ["ثلاجة", "muzlatgich"],
  ["غسالة", "kir yuvish mashinasi"],
  ["غسالة أطباق", "idish yuvish mashinasi"],
  ["مكنسة", "supurgi"],
  ["مكنسة كهربائية", "chang yutgich"],
  ["دلو", "chelak"],
  ["سلة", "savat"],
  ["حاوية نفايات", "axlat idishi"],
  ["صابون", "sovun"],
  ["شامبو", "shampun"],
  ["فرشاة أسنان", "tish cho'tkasi"],
  ["معجون أسنان", "tish pastasi"],
  ["منشفة", "sochiq"],
  ["مرآة", "oyna (ko'zgu)"],
  ["ماء ساخن", "issiq suv"],
  ["ماء بارد", "sovuq suv"],
  ["دش", "dush"],
  ["حوض", "rakovina"],
  ["حنفية", "kran"],
  ["مرحاض", "unitaz"],
  ["سخان", "isitkich"],
  ["تدفئة", "isitish tizimi"],
  ["مخزن", "omborxona"],
  ["مرآب", "garaj"],
  ["حديقة", "hovli/bog'"],
  ["سور", "tashqi devor"],
  ["بوابة", "darvoza"],
  ["مولد كهرباء", "generator"],
  ["عداد كهرباء", "elektr hisoblagich"],
  ["فاتورة", "hisob-qog'oz"],
  ["إنارة", "yoritish"],
  ["لمبة", "lampochka"],
  ["مفتاح كهرباء", "kalit (elektr)"],
  ["مقبس", "rozetka"],
  ["سلك", "sim"],
  ["جرس", "qo'ng'iroq"],
  ["كاميرا مراقبة", "kuzatuv kamerasi"],
  ["إنذار", "signal/sirena"],
  ["باب خشبي", "yog'och eshik"],
  ["باب حديدي", "temir eshik"],
  ["مكعبات ثلج", "muz kublari"],
  ["غسيل", "kir yuvish"],
  ["تجفيف", "quritish"],
  ["تنظيف", "tozalash"],
  ["ترتيب", "tartibga solish"],
  ["عطل", "nosozlik"],
  ["صيانة", "texnik xizmat"],
  ["عامل نظافة", "farrosh"],
  ["بواب", "darvozabon"],
  ["جار", "qo'shni"],
  ["طابق", "qavat"],
  ["سكن", "yashash joyi"],
  ["عمارة", "ko'p qavatli bino"],
  ["فلة", "uy (kottej)"],
  ["ساحة", "hovli maydoni"],
];