// ===========================================================
// SMART TA'LIM — Lug'at 9-qism (Sayohat va transport)
// Format: [inglizcha, o'zbekcha]
// ===========================================================

const LUGAT_TRAVEL = [
  // Transport vositalari
  ["car", "mashina"],
  ["bus", "avtobus"],
  ["train", "poyezd"],
  ["plane", "samolyot"],
  ["airplane", "aeroplan"],
  ["ship", "kema"],
  ["boat", "qayiq"],
  ["bicycle", "velosiped"],
  ["motorcycle", "mototsikl"],
  ["taxi", "taksi"],
  ["truck", "yuk mashinasi"],
  ["subway", "metro"],
  ["tram", "tramvay"],
  ["helicopter", "vertolyot"],
  ["lorry", "yuk mashinasi"],
  ["van", "furgon"],
  ["scooter", "samokat"],
  ["wagon", "vagon"],
  ["camel", "tuya"],
  ["donkey", "eshak"],

  // Yo'l va harakat
  ["road", "yo'l"],
  ["street", "ko'cha"],
  ["highway", "magistral yo'l"],
  ["bridge", "ko'prik"],
  ["crosswalk", "piyodalar o'tish joyi"],
  ["traffic light", "svetofor"],
  ["traffic jam", "tirbandlik"],
  ["intersection", "chorraha"],
  ["turn", "burilish"],
  ["direction", "yo'nalish"],
  ["distance", "masofa"],
  ["route", "marshrut"],
  ["map", "xarita"],
  ["ticket", "chipta"],
  ["station", "beksat/stantsiya"],
  ["stop", "to'xtash joyi"],
  ["airport", "aeroport"],
  ["seaport", "dengiz porti"],
  ["luggage", "bagaj"],
  ["suitcase", "chemodan"],

  // Sayohat mavzusi
  ["travel", "sayohat"],
  ["trip", "safar"],
  ["journey", "sayohat"],
  ["tourist", "turist"],
  ["tour", "tur"],
  ["guide", "gid"],
  ["hotel", "mehmonxona"],
  ["hostel", "yotoqxona (mehmonxona)"],
  ["reservation", "buyurtma"],
  ["booking", "band qilish"],
  ["passport", "pasport"],
  ["visa", "viza"],
  ["customs", "bojxona"],
  ["border", "chegara"],
  ["flight", "reys/parvoz"],
  ["boarding", "mindirish"],
  ["arrival", "kelish"],
  ["departure", "ketish"],
  ["delay", "kechikish"],
  ["destination", "manzil"],

  // Shahar joylari
  ["city", "shahar"],
  ["capital", "poytaxt"],
  ["center", "markaz"],
  ["square", "maydon"],
  ["park", "bog'"],
  ["museum", "muzey"],
  ["cinema", "kinoteatr"],
  ["theater", "teatr"],
  ["restaurant", "restoran"],
  ["cafe", "kafe"],
  ["supermarket", "supermarket"],
  ["market", "bozor"],
  ["bank", "bank"],
  ["post office", "pochta"],
  ["hospital", "kasalxona"],
  ["pharmacy", "dorixona"],
  ["police station", "politsiya bo'limi"],
  ["embassy", "elchixona"],
  ["library", "kutubxona"],
  ["monument", "haykal/yodgorlik"],
];