// ===========================================================
// SMART TA'LIM — Lug'at 4-qism (Oziq-ovqat va ichimliklar)
// Format: [inglizcha, o'zbekcha]
// ===========================================================

const LUGAT_FOOD = [
  // Meva va rezavorlar
  ["apple", "olma"],
  ["banana", "banan"],
  ["orange", "apelsin"],
  ["lemon", "limon"],
  ["grape", "uzum"],
  ["melon", "qovun"],
  ["watermelon", "tarvuz"],
  ["peach", "shaftoli"],
  ["pear", "nok"],
  ["cherry", "olcha/gilos"],
  ["plum", "olxo'ri"],
  ["apricot", "o'rik"],
  ["strawberry", "qulupnay"],
  ["pomegranate", "anor"],
  ["fig", "anjir"],
  ["date", "xurmo"],
  ["kiwi", "kivi"],
  ["pineapple", "ananas"],
  ["mango", "mango"],
  ["quince", "behi"],

  // Sabzavotlar
  ["tomato", "pomidor"],
  ["potato", "kartoshka"],
  ["cucumber", "bodring"],
  ["carrot", "sabzi"],
  ["onion", "piyoz"],
  ["garlic", "sarimsoq"],
  ["cabbage", "karam"],
  ["pepper", "qalampir"],
  ["eggplant", "baqlajon"],
  ["pumpkin", "qovoq"],
  ["radish", "turp"],
  ["beetroot", "lavlagi"],
  ["corn", "makkajo'xori"],
  ["peas", "no'xat"],
  ["beans", "loviya"],
  ["mushroom", "qo'ziqorin"],
  ["spinach", "isnaloq"],
  ["lettuce", "salat bargi"],
  ["dill", "shoyi"],
  ["parsley", "petrushka"],

  // Go'sht, sut va oziq-ovqat mahsulotlari
  ["meat", "go'sht"],
  ["beef", "mol go'shti"],
  ["chicken", "tovuq go'shti"],
  ["fish", "baliq"],
  ["egg", "tuxum"],
  ["milk", "sut"],
  ["yogurt", "qatiq"],
  ["cream", "qaymoq"],
  ["butter", "sariyog'"],
  ["cheese", "pishloq"],
  ["bread", "non"],
  ["flour", "un"],
  ["rice", "guruch"],
  ["pasta", "makaron"],
  ["salt", "tuz"],
  ["sugar", "shakar"],
  ["honey", "asal"],
  ["oil", "yog'"],
  ["sausage", "kolbasa"],
  ["soup", "sho'rva"],

  // Ichimliklar
  ["tea", "choy"],
  ["coffee", "qahva"],
  ["juice", "sharbat"],
  ["water", "suv"],
  ["milk shake", "milkshayk"],
  ["lemonade", "limonad"],
  ["cocoa", "kakao"],
  ["kefir", "kefir"],
  ["compote", "kompot"],
  ["soda", "gazli suv"],

  // Shirinliklar va yeguliklar
  ["cake", "tort"],
  ["candy", "konfet"],
  ["cookie", "pechenye"],
  ["chocolate", "shokolad"],
  ["ice cream", "muzqaymoq"],
  ["jam", "murabbo"],
  ["halva", "holva"],
  ["nuts", "yong'oqlar"],
  ["spring rolls", "somsa"],
  ["pie", "pirog"],

  // Xushbo'y va ziravorlar
  ["cumin", "zira"],
  ["cinnamon", "dolchin"],
  ["ginger", "zanjabil"],
  ["basil", "rayhon"],
  ["mint", "yalpiz"],
  ["vinegar", "sirka"],
  ["mustard", "xantal"],
  ["mayonnaise", "mayonez"],
  ["ketchup", "ketchup"],
  ["sauce", "sous"],
];