// ===========================================================
// SMART TA'LIM — Arab tili 13-qism (Sayohat va transport)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR13 = [
  ["سفر", "safar"],
  ["رحلة", "sayohat"],
  ["سياحة", "turizm"],
  ["سائح", "turist"],
  ["مسافر", "sayohatchi/yo'lovchi"],
  ["حقيبة", "chamadon"],
  ["جواز سفر", "pasport"],
  ["تأشيرة", "viza"],
  ["تذكرة", "chipta"],
  ["حجز", "bron"],
  ["إلغاء", "bekor qilish"],
  ["رحلة جوية", "aviaparvoz"],
  ["طائرة", "samolyot"],
  ["مطار", "aeroport"],
  ["طيار", "uchuvchi"],
  ["مضيفة طيران", "styuardessa"],
  ["ركوب الطائرة", "samolyotga chiqish"],
  ["ركاب", "yo'lovchilar"],
  ["أمتعة", "bagaj"],
  ["هبوط", "qo'nish"],
  ["إقلاع", "uchish"],
  ["تأخير", "kechikish"],
  ["إلغاء الرحلة", "parvozni bekor qilish"],
  ["قطار", "poyezd"],
  ["محطة قطار", "temir yo'l stantsiyasi"],
  ["قضبان", "rels"],
  ["رصيف", "perron"],
  ["عربة", "vagon"],
  ["مقعد", "o'rindiq"],
  ["سيارة", "mashina"],
  ["حافلة", "avtobus"],
  ["تاكسي", "taksi"],
  ["مترو", "metro"],
  ["ترام", "tramvay"],
  ["دراجة هوائية", "velosiped"],
  ["دراجة نارية", "mototsikl"],
  ["شاحنة", "yuk mashinasi"],
  ["سفينة", "kema"],
  ["قارب", "qayiq"],
  ["ميناء", "port"],
  ["مرسى", "pirs"],
  ["بحرية", "dengiz floti"],
  ["شارع", "ko'cha"],
  ["طريق", "yo'l"],
  ["شارع رئيسي", "bosh ko'cha"],
  ["زقاق", "tor ko'cha"],
  ["جسر", "ko'prik"],
  ["نفق", "tunnel"],
  ["مفترق", "chorraha"],
  ["إشارة مرور", "svetofor"],
  ["إشارات الطريق", "yo'l belgilari"],
  ["رصيف المشاة", "yo'lka"],
  ["ممر مشاة", "piyodalar o'tish joyi"],
  ["فحص جواز السفر", "pasport tekshiruvi"],
  ["جمرك", "bojxona"],
  ["حدود", "chegara"],
  ["مرور", "tirbandlik"],
  ["زحام", "olomon"],
  ["موقف السيارات", "avtoturargoh"],
  ["وقود", "yoqilg'i"],
  ["بنزين", "benzin"],
  ["عطل", "nosozlik"],
  ["إصلاح", "ta'mirlash"],
  ["فندق", "mehmonxona"],
  ["استقبال", "repseshn"],
  ["غرفة مفردة", "bir kishilik xona"],
  ["غرفة مزدوجة", "ikki kishilik xona"],
  ["استيقاظ", "uyg'otish xizmati"],
  ["فطور", "nonushta"],
  ["تشيك إن", "ro'yxatdan o'tish"],
  ["تشيك أوت", "chiqish"],
  ["ضيافة", "mehmondo'stlik"],
  ["وجهة", "manzil (yo'nalish)"],
  ["خريطة", "xarita"],
  ["بوصلة", "kompas"],
  ["معلم سياحي", "sayyohlik maskani"],
  ["زيارات", "tashriflar"],
  ["جولة", "ekskursiya"],
  ["مرشد سياحي", "gid"],
  ["هدية تذكارية", "esdalik sovg'a"],
  ["صورة", "surat"],
  ["ذكريات", "xotiralar"],
  ["إقامة", "turar joy"],
  ["إيجار سيارة", "avtomobil ijarasi"],
  ["محطة حافلات", "avtobekat"],
  ["وقف", "to'xtash"],
  ["انعطاف", "burilish"],
  ["مباشرة", "to'g'ridan-to'g'ri"],
  ["تحويل", "ulash (transfer)"],
  ["رحلات داخلية", "ichki reyslar"],
  ["رحلات دولية", "xalqaro reyslar"],
  ["بوابة", "darvoza (gate)"],
  ["منطقة الانتظار", "kutish zali"],
  ["مقعد نافذة", "deraza oldi (o'rindiq)"],
  ["مقعد ممر", "koridor yonidagi o'rindiq"],
  ["رسوم تأشيرة", "viza to'lovi"],
  ["إعلان الرحلة", "reys e'loni"],
  ["لوحة القيادة", "tablo"],
  ["تأمين السفر", "sayohat sug'urtasi"],
  ["عملة", "valyuta"],
  ["صرف العملة", "valyuta ayirboshlash"],
  ["صرّاف آلي", "bankomat"],
  ["مغادرة", "ketish (chiquv)"],
  ["وصول", "kelish"],
  ["صعود الطائرة", "samoletga chiqish (boarding)"],
  ["محطة أنفاق", "metro bekat"],
  ["شبكة مواصلات", "transport tarmog'i"],
];