// ===========================================================
// SMART TA'LIM — Arab tili 9-qism (Tabiat va ob-havo)
// Format: [arabcha, o'zbekcha]
// ===========================================================

const LUGAT_AR9 = [
  ["طبيعة", "tabiat"],
  ["بيئة", "atrof-muhit"],
  ["طقس", "ob-havo"],
  ["مناخ", "iqlim"],
  ["جو", "atmosfera"],
  ["حرارة", "issiqlik"],
  ["برودة", "sovuqlik"],
  ["رطوبة", "namlik"],
  ["جفاف", "quruqlik"],
  ["شمس", "quyosh"],
  ["أشعة الشمس", "quyosh nurlari"],
  ["ظل", "soya"],
  ["قمر", "oy"],
  ["هلال", "yangi oy"],
  ["بدر", "to'lin oy"],
  ["نجم", "yulduz"],
  ["كوكب", "sayyora"],
  ["فضاء", "koinot"],
  ["سماء", "osmon"],
  ["أفق", "ufq"],
  ["سحاب", "bulut"],
  ["غيم", "bulutlar"],
  ["ضباب", "tuman"],
  ["ندى", "shabnam"],
  ["مطر", "yomg'ir"],
  ["رذاذ", "mayda yomg'ir"],
  ["عاصفة مطر", "yomg'ir bo'roni"],
  ["ثلج", "qor"],
  ["تساقط الثلوج", "qor yog'ishi"],
  ["برد", "do'l"],
  ["جليد", "muz"],
  ["صقيع", "ayoz"],
  ["ريح", "shamol"],
  ["نسمة", "shabada"],
  ["عاصفة", "bo'ron"],
  ["إعصار", "to'fon/uyurma"],
  ["زوبعة", "dovul"],
  ["غبار", "chang"],
  ["رعد", "momaqaldiroq"],
  ["برق", "chaqmoq"],
  ["قوس قزح", "kamalak"],
  ["فيضان", "suv toshqini"],
  ["زلزال", "zilzila"],
  ["بركان", "vulqon"],
  ["ثوران", "otilish (vulqon)"],
  ["صحراء", "cho'l"],
  ["كثبان رملية", "qum tepaligi"],
  ["واحة", "voha"],
  ["جبل", "tog'"],
  ["قمة", "cho'qqi"],
  ["سفح", "yon bag'ir"],
  ["واد", "vodiy"],
  ["تل", "tepalik"],
  ["هضبة", "plato"],
  ["سهل", "tekislik"],
  ["مرعى", "yaylov"],
  ["غابة", "o'rmon"],
  ["أشجار", "daraxtlar"],
  ["شجرة", "daraxt"],
  ["جذع", "daraxt tanasi"],
  ["غصن", "shox"],
  ["ورقة", "barg"],
  ["أوراق", "barglar"],
  ["زهرة", "gul"],
  ["وردة", "atirgul"],
  ["زنبق", "nilufar"],
  ["نرجس", "narzis"],
  ["توليب", "lola"],
  ["عشب", "o't"],
  ["حشيش", "yovvoyi o't"],
  ["قمح", "bug'doy"],
  ["شعير", "arpa"],
  ["زراعة", "dehqonchilik"],
  ["نهر", "daryo"],
  ["جدول", "ariq"],
  ["بحيرة", "ko'l"],
  ["بحر", "dengiz"],
  ["محيط", "okean"],
  ["خليج", "ko'rfaz"],
  ["مضيق", "bo'g'iz (dengiz)"],
  ["جزيرة", "orol"],
  ["شاطئ", "sohil/plyaj"],
  ["موجة", "to'lqin"],
  ["مد", "suv ko'tarilishi"],
  ["جزر", "suv qaytishi"],
  ["صخرة", "qoya"],
  ["حجر", "tosh"],
  ["حصى", "shag'al"],
  ["رمل", "qum"],
  ["طين", "loy"],
  ["تراب", "tuproq"],
  ["معدن", "mineral"],
  ["ذهب", "oltin"],
  ["فضة", "kumush"],
  ["حديد", "temir"],
  ["ألماس", "olmos"],
  ["فحم", "ko'mir"],
  ["نفط", "neft"],
  ["غاز", "gaz"],
  ["طاقة", "energiya"],
  ["مورد طبيعي", "tabiiy boylik"],
  ["محمية طبيعية", "qo'riqxona"],
  ["هواء نقي", "toza havo"],
  ["تلوث", "ifloslanish"],
  ["مخلفات", "chiqindilar"],
  ["إعادة تدوير", "qayta ishlash"],
  ["بيئة نظيفة", "toza muhit"],
];